[[changelog]]
Changelog
---------

[[graylog-2.0.2]]
Graylog 2.0.2
~~~~~~~~~~~~~

Released: 2016-05-27

https://www.graylog.org/blog/57-graylog-v2-0-2-released

*Improvements*

* Improved user form.
https://github.com/Graylog2/graylog2-server/issues/2261[Graylog2/graylog2-server#2261]
* Improved logging of plugin list on server startup.
https://github.com/Graylog2/graylog2-server/issues/2290[Graylog2/graylog2-server#2290]
* Forbid empty passwords when using LDAP.
https://github.com/Graylog2/graylog2-server/issues/2214[Graylog2/graylog2-server#2214]
https://github.com/Graylog2/graylog2-server/issues/2283[Graylog2/graylog2-server#2283]
* Improved metrics page.
https://github.com/Graylog2/graylog2-server/issues/2250[Graylog2/graylog2-server#2250]
https://github.com/Graylog2/graylog2-server/issues/2255[Graylog2/graylog2-server#2255]
* Improved search histogram resolution auto selection.
https://github.com/Graylog2/graylog2-server/issues/2148[Graylog2/graylog2-server#2148]
https://github.com/Graylog2/graylog2-server/issues/2289[Graylog2/graylog2-server#2289]
* Improved cluster overview page.
https://github.com/Graylog2/graylog2-server/issues/2291[Graylog2/graylog2-server#2291]

*Bug Fixes*

* Fixed concurrency issue with Drools.
https://github.com/Graylog2/graylog2-server/issues/2119[Graylog2/graylog2-server#2119]
https://github.com/Graylog2/graylog2-server/issues/2188[Graylog2/graylog2-server#2188]
https://github.com/Graylog2/graylog2-server/issues/2231[Graylog2/graylog2-server#2231]
* Fixed problems with Internet Explorer.
https://github.com/Graylog2/graylog2-server/issues/2246[Graylog2/graylog2-server#2246]
* Fixed issues with old dashboards.
https://github.com/Graylog2/graylog2-server/issues/2262[Graylog2/graylog2-server#2262]
https://github.com/Graylog2/graylog2-server/issues/2163[Graylog2/graylog2-server#2163]
* Fixed changing log levels via REST API.
https://github.com/Graylog2/graylog2-server/issues/1904[Graylog2/graylog2-server#1904]
https://github.com/Graylog2/graylog2-server/issues/2277[Graylog2/graylog2-server#2277]
* Fixed plugin inter-dependencies by using one class loader for all
plugins.
https://github.com/Graylog2/graylog2-server/issues/2280[Graylog2/graylog2-server#2280]

*Plugin: Pipeline Processor*

* Add syslog related rule functions.
https://github.com/Graylog2/graylog-plugin-pipeline-processor/issues/19[Graylog2/graylog-plugin-pipeline-processor#19]
* Add concat rule functions.
https://github.com/Graylog2/graylog-plugin-pipeline-processor/issues/20[Graylog2/graylog-plugin-pipeline-processor#20]
* Fixed problem with IP address function.
https://github.com/Graylog2/graylog-plugin-pipeline-processor/issues/28[Graylog2/graylog-plugin-pipeline-processor#28]
https://github.com/Graylog2/graylog-plugin-pipeline-processor/issues/32[Graylog2/graylog-plugin-pipeline-processor#32]
* Properly unescape strings in raw literals.
https://github.com/Graylog2/graylog-plugin-pipeline-processor/issues/30[Graylog2/graylog-plugin-pipeline-processor#30]
https://github.com/Graylog2/graylog-plugin-pipeline-processor/issues/31[Graylog2/graylog-plugin-pipeline-processor#31]

[[graylog-2.0.1]]
Graylog 2.0.1
~~~~~~~~~~~~~

Released: 2016-05-11

https://www.graylog.org/blog/56-graylog-v2-0-1-released

*Improvements*

* Improved session handling.
https://github.com/Graylog2/graylog2-server/issues/2157[Graylog2/graylog2-server#2157]
* Included UPGRADING file in the build artifact.
https://github.com/Graylog2/graylog2-server/issues/2170[Graylog2/graylog2-server#2170]
* Added rotation/retention settings back to the config file.
https://github.com/Graylog2/graylog2-server/issues/2181[Graylog2/graylog2-server#2181]
* Improved proxy setup configuration settings.
https://github.com/Graylog2/graylog2-server/issues/2156[Graylog2/graylog2-server#2156]
* Forbid wildcard host in rest_transport_uri.
https://github.com/Graylog2/graylog2-server/issues/2205[Graylog2/graylog2-server#2205]
* Improved robustness for unreachable nodes.
https://github.com/Graylog2/graylog2-server/issues/2206[Graylog2/graylog2-server#2206]
* Use a more lightweight API to get all index names and aliases.
https://github.com/Graylog2/graylog2-server/issues/2194[Graylog2/graylog2-server#2194]
https://github.com/Graylog2/graylog2-server/issues/2210[Graylog2/graylog2-server#2210]

*Bug Fixes*

* Fixed some documentation links.
* Fixed inverted stream rules.
https://github.com/Graylog2/graylog2-server/issues/2160[Graylog2/graylog2-server#2160]
https://github.com/Graylog2/graylog2-server/issues/2172[Graylog2/graylog2-server#2172]
* Fixed swallowed LDAP authentication exception.
https://github.com/Graylog2/graylog2-server/issues/2176[Graylog2/graylog2-server#2176]
https://github.com/Graylog2/graylog2-server/issues/2178[Graylog2/graylog2-server#2178]
* Fixed insecure handling of PID files. Thanks
https://github.com/juergenhoetzel[@juergenhoetzel]!
https://github.com/Graylog2/graylog2-server/issues/2174[Graylog2/graylog2-server#2174]
* Fixed alert conditions that have been created in Graylog 1.x.
https://github.com/Graylog2/graylog2-server/issues/2169[Graylog2/graylog2-server#2169]
https://github.com/Graylog2/graylog2-server/issues/2182[Graylog2/graylog2-server#2182]
* Fixed setting of application context.
https://github.com/Graylog2/graylog2-server/issues/2191[Graylog2/graylog2-server#2191]
https://github.com/Graylog2/graylog2-server/issues/2208[Graylog2/graylog2-server#2208]
* Fixed setting of custom Elasticsearch analyzer.
https://github.com/Graylog2/graylog2-server/issues/2209[Graylog2/graylog2-server#2209]
* Fixed masking of password config values in the web interface.
https://github.com/Graylog2/graylog2-server/issues/2198[Graylog2/graylog2-server#2198]
https://github.com/Graylog2/graylog2-server/issues/2203[Graylog2/graylog2-server#2203]
* Fixed URL handling.
https://github.com/Graylog2/graylog2-server/issues/2200[Graylog2/graylog2-server#2200]
https://github.com/Graylog2/graylog2-server/issues/2213[Graylog2/graylog2-server#2213]

*Plugin: Collector*

* Rotate nxlog logfiles once a day by default.
* Add GELF TCP output for nxlog.

[[graylog-2.0.0]]
Graylog 2.0.0
~~~~~~~~~~~~~

Released: 2016-04-27

https://www.graylog.org/blog/55-announcing-graylog-v2-0-ga

__________________________________________________________________
*note*

Please make sure to read the Upgrade Guide <upgrade-from-1-to-2>::
  before upgrading to Graylog 2.0. There are breaking changes!
__________________________________________________________________

*Feature Highlights*

See the release announcement for details on the new features.

* Web interface no longer a separate process
* Support for Elasticsearch 2.x
* Live tail support
* Message Processing Pipeline
* Map Widget Plugin
* Collector Sidecar
* Streams filter UI
* Search for surrounding messages
* Query range limit
* Configurable query time ranges
* Archiving (commercial feature)

*Bug Fixes*

There have been lots of bug fixes since the 1.3 releases. We only list
the ones that we worked on since the 2.0 alpha phase.

* Fixed issues with search page pagination and number of returned
results:
https://github.com/Graylog2/graylog2-server/issues/1759[Graylog2/graylog2-server#1759],
https://github.com/Graylog2/graylog2-server/issues/1775[Graylog2/graylog2-server#1775],
and
https://github.com/Graylog2/graylog2-server/issues/1802[Graylog2/graylog2-server#1802]
* Avoid creating MongoDB collection multiple times:
https://github.com/Graylog2/graylog2-server/issues/1747[Graylog2/graylog2-server#1747]
* Removed number of connected nodes in login page:
https://github.com/Graylog2/graylog2-server/issues/1732[Graylog2/graylog2-server#1732]
* Fix dynamic search result histogram resolution:
https://github.com/Graylog2/graylog2-server/issues/1764[Graylog2/graylog2-server#1764]
* Show overlay in Graylog web interface when Graylog server is not
available:
https://github.com/Graylog2/graylog2-server/issues/1762[Graylog2/graylog2-server#1762]
* Fix metric types:
https://github.com/Graylog2/graylog2-server/issues/1784[Graylog2/graylog2-server#1784]
* Only load all metrics on demand:
https://github.com/Graylog2/graylog2-server/issues/1782[Graylog2/graylog2-server#1782]
* Activate search refresh after selecting a refresh interval:
https://github.com/Graylog2/graylog2-server/issues/1796[Graylog2/graylog2-server#1796]
* Fix circular dependencies:
https://github.com/Graylog2/graylog2-server/issues/1789[Graylog2/graylog2-server#1789]
* Only render input forms when input type is available:
https://github.com/Graylog2/graylog2-server/issues/1798[Graylog2/graylog2-server#1798]
* Document web interface configuration settings in graylog.conf.
https://github.com/Graylog2/graylog2-server/issues/1777[Graylog2/graylog2-server#1777]
* Fix roles link to documentation.
https://github.com/Graylog2/graylog2-server/issues/1805[Graylog2/graylog2-server#1805]
* Fix issue with field graphs.
https://github.com/Graylog2/graylog2-server/issues/1811[Graylog2/graylog2-server#1811]
* Fix search result pagination.
https://github.com/Graylog2/graylog2-server/issues/1812[Graylog2/graylog2-server#1812]
* Fix add to query button on quick values.
https://github.com/Graylog2/graylog2-server/issues/1797[Graylog2/graylog2-server#1797]
* Fix URL to Graylog marketplace on content pack export page.
https://github.com/Graylog2/graylog2-server/issues/1817[Graylog2/graylog2-server#1817]
* Fix elasticsearch node name for the Graylog client node.
https://github.com/Graylog2/graylog2-server/issues/1814[Graylog2/graylog2-server#1814]
and
https://github.com/Graylog2/graylog2-server/issues/1820[Graylog2/graylog2-server#1820]
* Fix widget sorting for dashboards.
* Use _ as default key separator in JSON Extractor.
https://github.com/Graylog2/graylog2-server/issues/1841[Graylog2/graylog2-server#1841]
* Clarify that Graylog Collector needs access to rest_listen_uri.
https://github.com/Graylog2/graylog2-server/issues/1847[Graylog2/graylog2-server#1847]
* Fix potential memory leak in GELF UDP handler.
https://github.com/Graylog2/graylog2-server/issues/1857[Graylog2/graylog2-server#1857]
https://github.com/Graylog2/graylog2-server/issues/1862[Graylog2/graylog2-server#1862]
* Fix user with correct permissions not allowed to view stream:
https://github.com/Graylog2/graylog2-server/issues/1887[Graylog2/graylog2-server#1887],
https://github.com/Graylog2/graylog2-server/issues/1902[Graylog2/graylog2-server#1902]
* Make pattern to check Graylog-managed indices stricter:
https://github.com/Graylog2/graylog2-server/issues/1882[Graylog2/graylog2-server#1882],
https://github.com/Graylog2/graylog2-server/issues/1888[Graylog2/graylog2-server#1888]
* Fix throughput counter:
https://github.com/Graylog2/graylog2-server/issues/1876[Graylog2/graylog2-server#1876]
* Fix replay search link in dashboards:
https://github.com/Graylog2/graylog2-server/issues/1835[Graylog2/graylog2-server#1835]
* Render server unavailable page more reliably:
https://github.com/Graylog2/graylog2-server/issues/1867[Graylog2/graylog2-server#1867]
* Fix build issue with maven.
https://github.com/Graylog2/graylog-server2/issues/1907[Graylog2/graylog-server2#1907]
(Thanks @gitfrederic)
* Fix username in REST API access logs.
https://github.com/Graylog2/graylog-server2/issues/1815[Graylog2/graylog-server2#1815]
https://github.com/Graylog2/graylog-server2/issues/1918[Graylog2/graylog-server2#1918]
(Thanks @mikkolehtisalo)
* Fix alert annotations in message histogram.
https://github.com/Graylog2/graylog-server2/issues/1921[Graylog2/graylog-server2#1921]
* Fix problem with automatic input form reload.
https://github.com/Graylog2/graylog-server2/issues/1870[Graylog2/graylog-server2#1870]
https://github.com/Graylog2/graylog-server2/issues/1929[Graylog2/graylog-server2#1929]
* Fix asset caching.
https://github.com/Graylog2/graylog-server2/issues/1924[Graylog2/graylog-server2#1924]
https://github.com/Graylog2/graylog-server2/issues/1930[Graylog2/graylog-server2#1930]
* Fix issue with cursor jumps in the search bar.
https://github.com/Graylog2/graylog-server2/issues/1911[Graylog2/graylog-server2#1911]
* Fix import of Graylog 1.x extractors.
https://github.com/Graylog2/graylog-server2/issues/1831[Graylog2/graylog-server2#1831]
https://github.com/Graylog2/graylog-server2/issues/1937[Graylog2/graylog-server2#1937]
* Field charts will now use the stream and time range of the current
search.
https://github.com/Graylog2/graylog-server2/issues/1785[Graylog2/graylog-server2#1785]
https://github.com/Graylog2/graylog2-web-interface/issues/1620[Graylog2/graylog2-web-interface#1620]
https://github.com/Graylog2/graylog2-web-interface/issues/1618[Graylog2/graylog2-web-interface#1618]
https://github.com/Graylog2/graylog2-web-interface/issues/1485[Graylog2/graylog2-web-interface#1485]
https://github.com/Graylog2/graylog-server2/issues/1938[Graylog2/graylog-server2#1938]
* Improve browser validations.
https://github.com/Graylog2/graylog-server2/issues/1885[Graylog2/graylog-server2#1885]
* Fix Internet Explorer support.
https://github.com/Graylog2/graylog-server2/issues/1935[Graylog2/graylog-server2#1935]
* Fix issue where a user was logged out when accessing an unauthorized
resource.
https://github.com/Graylog2/graylog-server2/issues/1944[Graylog2/graylog-server2#1944]
* Fix issue with surrounding search.
https://github.com/Graylog2/graylog-server2/issues/1946[Graylog2/graylog-server2#1946]
* Fix problem deleting dashboard widget where the plugin got removed.
https://github.com/Graylog2/graylog-server2/issues/1943[Graylog2/graylog-server2#1943]
* Fix permission issue on user edit page.
https://github.com/Graylog2/graylog-server2/issues/1964[Graylog2/graylog-server2#1964]
* Fix histogram time range selection via mouse.
https://github.com/Graylog2/graylog-server2/issues/1895[Graylog2/graylog-server2#1895]
* Fix problems with duplicate Reflux store instances.
https://github.com/Graylog2/graylog-server2/issues/1967[Graylog2/graylog-server2#1967]
* Create PID file earlier in the startup process.
https://github.com/Graylog2/graylog-server2/issues/1969[Graylog2/graylog-server2#1969]
https://github.com/Graylog2/graylog-server2/issues/1978[Graylog2/graylog-server2#1978]
* Fix content type detection for static assets.
https://github.com/Graylog2/graylog-server2/issues/1982[Graylog2/graylog-server2#1982]
https://github.com/Graylog2/graylog-server2/issues/1983[Graylog2/graylog-server2#1983]
* Fix caching of static assets.
https://github.com/Graylog2/graylog-server2/issues/1982[Graylog2/graylog-server2#1982]
https://github.com/Graylog2/graylog-server2/issues/1983[Graylog2/graylog-server2#1983]
* Show error message on malformed search query.
https://github.com/Graylog2/graylog-server2/issues/1896[Graylog2/graylog-server2#1896]
* Fix parsing of GELF chunks.
https://github.com/Graylog2/graylog-server2/issues/1986[Graylog2/graylog-server2#1986]
* Fix problems editing reader users profile.
https://github.com/Graylog2/graylog-server2/issues/1984[Graylog2/graylog-server2#1984]
https://github.com/Graylog2/graylog-server2/issues/1987[Graylog2/graylog-server2#1987]
* Fix problem with lost extractors and static fields on input update.
https://github.com/Graylog2/graylog-server2/issues/1988[Graylog2/graylog-server2#1988]
https://github.com/Graylog2/graylog-server2/issues/1923[Graylog2/graylog-server2#1923]
* Improve fetching cluster metrics to avoid multiple HTTP calls.
https://github.com/Graylog2/graylog-server2/issues/1974[Graylog2/graylog-server2#1974]
https://github.com/Graylog2/graylog-server2/issues/1990[Graylog2/graylog-server2#1990]
* Properly handle empty messages.
https://github.com/Graylog2/graylog-server2/issues/1584[Graylog2/graylog-server2#1584]
https://github.com/Graylog2/graylog-server2/issues/1995[Graylog2/graylog-server2#1995]
* Add 100-Continue support to HTTP inputs.
https://github.com/Graylog2/graylog-server2/issues/1939[Graylog2/graylog-server2#1939]
https://github.com/Graylog2/graylog-server2/issues/1998[Graylog2/graylog-server2#1998]
* Fix setting dashboard as start page for reader users.
https://github.com/Graylog2/graylog-server2/issues/2005[Graylog2/graylog-server2#2005]
* Allow dots (".") in LDAP group name mappings.
https://github.com/Graylog2/graylog-server2/issues/1458[Graylog2/graylog-server2#1458]
https://github.com/Graylog2/graylog-server2/issues/2009[Graylog2/graylog-server2#2009]
* Update user edit form when username changes.
https://github.com/Graylog2/graylog-server2/issues/2000[Graylog2/graylog-server2#2000]
* Fix issue with permissions in user form.
https://github.com/Graylog2/graylog-server2/issues/1989[Graylog2/graylog-server2#1989]
* Update extractor example when message is loaded.
https://github.com/Graylog2/graylog-server2/issues/1957[Graylog2/graylog-server2#1957]
https://github.com/Graylog2/graylog-server2/issues/2013[Graylog2/graylog-server2#2013]
* Disable log4j2 shutdown hooks to avoid exception on shutdown.
https://github.com/Graylog2/graylog-server2/issues/1795[Graylog2/graylog-server2#1795]
https://github.com/Graylog2/graylog-server2/issues/2015[Graylog2/graylog-server2#2015]
* Fix styling issue with map widget.
https://github.com/Graylog2/graylog-server2/issues/2003[Graylog2/graylog-server2#2003]
* Fix openstreetmap URL in map widget.
https://github.com/Graylog2/graylog-server2/issues/1994[Graylog2/graylog-server2#1994]
* Fix problem with collector heartbeat validation.
https://github.com/Graylog2/graylog-server2/issues/2002[Graylog2/graylog-server2#2002]
https://github.com/Graylog2/graylog2-web-interface/issues/1726[Graylog2/graylog2-web-interface#1726]
https://github.com/Graylog2/graylog-plugin-collector/issues/3[Graylog2/graylog-plugin-collector#3]
* Remove unused command line parameters.
https://github.com/Graylog2/graylog-server2/issues/1977[Graylog2/graylog-server2#1977]
* Fixed timezone issues for date time processing in JSON parser.
https://github.com/Graylog2/graylog-server2/issues/2007[Graylog2/graylog-server2#2007]
* Fixed JavaScript error with field truncation.
https://github.com/Graylog2/graylog-server2/issues/2025[Graylog2/graylog-server2#2025]
* Fixed redirection if user is not authorized.
https://github.com/Graylog2/graylog-server2/issues/1985[Graylog2/graylog-server2#1985]
https://github.com/Graylog2/graylog-server2/issues/2024[Graylog2/graylog-server2#2024]
* Made changing the sort order in search result table work again.
https://github.com/Graylog2/graylog-server2/issues/2028[Graylog2/graylog-server2#2028]
https://github.com/Graylog2/graylog-server2/issues/2031[Graylog2/graylog-server2#2031]
* Performance improvements on "System/Indices" page.
https://github.com/Graylog2/graylog-server2/issues/2017[Graylog2/graylog-server2#2017]
* Fixed content-type settings for static assets.
https://github.com/Graylog2/graylog-server2/issues/2052[Graylog2/graylog-server2#2052]
* Fixed return code for invalid input IDs.
https://github.com/Graylog2/graylog-server2/issues/1718[Graylog2/graylog-server2#1718]
https://github.com/Graylog2/graylog-server2/issues/1767[Graylog2/graylog-server2#1767]
* Improved field analyzer UI.
https://github.com/Graylog2/graylog-server2/issues/2022[Graylog2/graylog-server2#2022]
https://github.com/Graylog2/graylog-server2/issues/2023[Graylog2/graylog-server2#2023]
* Fixed login with LDAP user.
https://github.com/Graylog2/graylog-server2/issues/2045[Graylog2/graylog-server2#2045]
https://github.com/Graylog2/graylog-server2/issues/2046[Graylog2/graylog-server2#2046]
https://github.com/Graylog2/graylog-server2/issues/2069[Graylog2/graylog-server2#2069]
* Fixed issue with bad message timestamps to avoid data loss.
https://github.com/Graylog2/graylog-server2/issues/2064[Graylog2/graylog-server2#2064]
https://github.com/Graylog2/graylog-server2/issues/2065[Graylog2/graylog-server2#2065]
* Improved handling of Elasticsearch indices.
https://github.com/Graylog2/graylog-server2/issues/2058[Graylog2/graylog-server2#2058]
https://github.com/Graylog2/graylog-server2/issues/2062[Graylog2/graylog-server2#2062]
* Extractor form improvements for JSON and Grok extractors.
https://github.com/Graylog2/graylog-server2/issues/1883[Graylog2/graylog-server2#1883]
https://github.com/Graylog2/graylog-server2/issues/2020[Graylog2/graylog-server2#2020]
* Used search refresh to refresh field statistics.
https://github.com/Graylog2/graylog-server2/issues/1961[Graylog2/graylog-server2#1961]
https://github.com/Graylog2/graylog-server2/issues/2068[Graylog2/graylog-server2#2068]
* Fixed clicking zoom button in quick values.
https://github.com/Graylog2/graylog-server2/issues/2040[Graylog2/graylog-server2#2040]
https://github.com/Graylog2/graylog-server2/issues/2067[Graylog2/graylog-server2#2067]
* Web interface styling improvements.
* Replaced . in message field keys with a _ for ES 2.x compatibility.
https://github.com/Graylog2/graylog-server2/issues/2078[Graylog2/graylog-server2#2078]
* Fixed unprocessed journal messages reload in node list.
https://github.com/Graylog2/graylog-server2/issues/2083[Graylog2/graylog-server2#2083]
* Fixed problems with stale sessions on the login page.
https://github.com/Graylog2/graylog-server2/issues/2073[Graylog2/graylog-server2#2073]
https://github.com/Graylog2/graylog-server2/issues/2059[Graylog2/graylog-server2#2059]
https://github.com/Graylog2/graylog-server2/issues/1891[Graylog2/graylog-server2#1891]
* Fixed issue with index retention strategies.
https://github.com/Graylog2/graylog-server2/issues/2100[Graylog2/graylog-server2#2100]
* Fixed password change form.
https://github.com/Graylog2/graylog-server2/issues/2103[Graylog2/graylog-server2#2103]
https://github.com/Graylog2/graylog-server2/issues/2105[Graylog2/graylog-server2#2105]
* Do not show search refresh controls on the sources page.
https://github.com/Graylog2/graylog-server2/issues/1821[Graylog2/graylog-server2#1821]
https://github.com/Graylog2/graylog-server2/issues/2104[Graylog2/graylog-server2#2104]
* Wait for index being available before calculating index range.
https://github.com/Graylog2/graylog-server2/issues/2061[Graylog2/graylog-server2#2061]
https://github.com/Graylog2/graylog-server2/issues/2098[Graylog2/graylog-server2#2098]
* Fixed issue with sorting extractors.
https://github.com/Graylog2/graylog-server2/issues/2086[Graylog2/graylog-server2#2086]
https://github.com/Graylog2/graylog-server2/issues/2088[Graylog2/graylog-server2#2088]
* Improve DataTable UI component.
https://github.com/Graylog2/graylog-plugin-pipeline-processor/issues/11[Graylog2/graylog-plugin-pipeline-processor#11]
* Move TCP keepalive setting into AbstractTcpTransport to simplify input
development.
https://github.com/Graylog2/graylog-server2/issues/2112[Graylog2/graylog-server2#2112]
* Fixed issue with Elasticsearch index template update.
https://github.com/Graylog2/graylog-server2/issues/2089[Graylog2/graylog-server2#2089]
https://github.com/Graylog2/graylog-server2/issues/2097[Graylog2/graylog-server2#2097]
* Ensure that tmpDir is writable when generating self-signed certs in
TCP transports.
https://github.com/Graylog2/graylog-server2/issues/2054[Graylog2/graylog-server2#2054]
https://github.com/Graylog2/graylog-server2/issues/2096[Graylog2/graylog-server2#2096]
* Fixed default values for plugin configuration forms.
https://github.com/Graylog2/graylog-server2/issues/2108[Graylog2/graylog-server2#2108]
https://github.com/Graylog2/graylog-server2/issues/2114[Graylog2/graylog-server2#2114]
* Dashboard usability improvements.
https://github.com/Graylog2/graylog-server2/issues/2093[Graylog2/graylog-server2#2093]
* Include default values in pluggable entities forms.
https://github.com/Graylog2/graylog-server2/issues/2122[Graylog2/graylog-server2#2122]
* Ignore empty authentication tokens in LdapUserAuthenticator.
https://github.com/Graylog2/graylog-server2/issues/2123[Graylog2/graylog-server2#2123]
* Add REST API authentication and permissions.
https://github.com/Graylog2/graylog-plugin-pipeline-processor/issues/15[Graylog2/graylog-plugin-pipeline-processor#15]
* Require authenticated user in REST resources.
https://github.com/Graylog2/graylog-plugin-pipeline-processor/issues/14[Graylog2/graylog-plugin-pipeline-processor#14]
* Lots of UI improvements in the web interface.
https://github.com/Graylog2/graylog-server2/issues/2136[Graylog2/graylog-server2#2136]
* Fixed link to REST API browser.
https://github.com/Graylog2/graylog-server2/issues/2133[Graylog2/graylog-server2#2133]
* Fixed CSV export skipping first chunk.
https://github.com/Graylog2/graylog-server2/issues/2128[Graylog2/graylog-server2#2128]
* Fixed updating content packs.
https://github.com/Graylog2/graylog-server2/issues/2138[Graylog2/graylog-server2#2138]
https://github.com/Graylog2/graylog-server2/issues/2141[Graylog2/graylog-server2#2141]
* Added missing 404 page.
https://github.com/Graylog2/graylog-server2/issues/2139[Graylog2/graylog-server2#2139]

[[graylog-1.3.4]]
Graylog 1.3.4
~~~~~~~~~~~~~

Released: 2016-03-16

https://www.graylog.org/blog/49-graylog-1-3-4-is-now-available

* Fix security issue which allowed redirecting users to arbitrary sites
on login
https://github.com/Graylog2/graylog2-web-interface/pull/1729[Graylog2/graylog2-web-interface#1729]
* Fix issue with time-based index rotation strategy
https://github.com/Graylog2/graylog2-server/issues/725[Graylog2/graylog2-server#725]
https://github.com/Graylog2/graylog2-server/pull/1693[Graylog2/graylog2-server#1693]
* Fix issue with `IndexFailureServiceImpl`
https://github.com/Graylog2/graylog2-server/issues/1747[Graylog2/graylog2-server#1747]
* Add default Content-Type to `GettingStartedResource`
https://github.com/Graylog2/graylog2-server/issues/1700[Graylog2/graylog2-server#1700]
* Improve OS platform detection
https://github.com/Graylog2/graylog2-server/issues/1737[Graylog2/graylog2-server#1737]
* Add prefixes `GRAYLOG_` (environment variables) and `graylog.` (system
properties) for overriding configuration settings
https://github.com/Graylog2/graylog2-server/commit/48ed88d4a7897152f7daa16f0d77e03b824d7b48[Graylog2/graylog2-server@48ed88d]
* Fix URL to Graylog Marketplace on Extractor/Content Pack pages
https://github.com/Graylog2/graylog2-server/issues/1817[Graylog2/graylog2-server#1817]
* Use monospace font on message values
https://github.com/Graylog2/graylog2-web-interface/commit/3cce368bd7360c0e95dc0b635cb99f0a47daa6ac[Graylog2/graylog2-web-interface@3cce368]

[[graylog-1.3.3]]
Graylog 1.3.3
~~~~~~~~~~~~~

Released: 2016-01-14

https://www.graylog.org/graylog-1-3-3-is-now-available/

* Absolute and relative time spans give different results
https://github.com/Graylog2/graylog2-server/issues/1572[Graylog2/graylog2-server#1572]
https://github.com/Graylog2/graylog2-server/issues/1463[Graylog2/graylog2-server#1463]
https://github.com/Graylog2/graylog2-server/issues/1672[Graylog2/graylog2-server#1672]
https://github.com/Graylog2/graylog2-server/pull/1679[Graylog2/graylog2-server#1679]
* Search result count widget not caching
https://github.com/Graylog2/graylog2-server/issues/1640[Graylog2/graylog2-server#1640]
https://github.com/Graylog2/graylog2-server/pull/1681[Graylog2/graylog2-server#1681]
* Field Value Condition Alert, does not permit decimal values
https://github.com/Graylog2/graylog2-server/issues/1657[Graylog2/graylog2-server#1657]
* Correctly handle null values in nested structures in JsonExtractor
https://github.com/Graylog2/graylog2-server/issues/1676[Graylog2/graylog2-server#1676]
https://github.com/Graylog2/graylog2-server/pull/1677[Graylog2/graylog2-server#1677]
* Add `Content-Type` and `X-Graylog2-No-Session-Extension` to CORS
headers
https://github.com/Graylog2/graylog2-server/issues/1682[Graylog2/graylog2-server#1682]
https://github.com/Graylog2/graylog2-server/pull/1685[Graylog2/graylog2-server#1685]
* Discard Message Output
https://github.com/Graylog2/graylog2-server/pull/1688[Graylog2/graylog2-server#1688]

[[graylog-1.3.2]]
Graylog 1.3.2
~~~~~~~~~~~~~

Released: 2015-12-18

https://www.graylog.org/graylog-1-3-2-is-now-available/

* Deserializing a blacklist filter (`FilterDescription`) leads to
`StackOverflowError`
https://github.com/Graylog2/graylog2-server/issues/1641[Graylog2/graylog2-server#1641]

[[graylog-1.3.1]]
Graylog 1.3.1
~~~~~~~~~~~~~

Released: 2015-12-17

https://www.graylog.org/graylog-1-3-1-is-now-available/

* Add option to AMQP transports to bind the queue to the exchange
https://github.com/Graylog2/graylog2-server/issues/1599[Graylog2/graylog2-server#1599]
https://github.com/Graylog2/graylog2-server/pull/1633[Graylog2/graylog2-server#1633]
* Install a Graylog index template instead of set mappings on index
creation
https://github.com/Graylog2/graylog2-server/issues/1624[Graylog2/graylog2-server#1624]
https://github.com/Graylog2/graylog2-server/pull/1628[Graylog2/graylog2-server#1628]

[[graylog-1.3.0]]
Graylog 1.3.0
~~~~~~~~~~~~~

Released: 2015-12-09

https://www.graylog.org/graylog-1-3-ga-is-ready/

* Allow index range calculation for a single index.
https://github.com/Graylog2/graylog2-server/issues/1451[Graylog2/graylog2-server#1451]
https://github.com/Graylog2/graylog2-server/issues/1455[Graylog2/graylog2-server#1455]
* Performance improvements for index ranges.
* Make internal server logs accessible via REST API.
https://github.com/Graylog2/graylog2-server/issues/1452[Graylog2/graylog2-server#1452]
* Make specific configuration values accessible via REST API.
https://github.com/Graylog2/graylog2-server/issues/1484[Graylog2/graylog2-server#1484]
* Added Replace Extractor.
https://github.com/Graylog2/graylog2-server/issues/1485[Graylog2/graylog2-server#1485]
* Added a default set of Grok patterns.
https://github.com/Graylog2/graylog2-server/issues/1495[Graylog2/graylog2-server#1495]
* Log operating system details on server startup.
https://github.com/Graylog2/graylog2-server/issues/1244[Graylog2/graylog2-server#1244]
https://github.com/Graylog2/graylog2-server/issues/1553[Graylog2/graylog2-server#1553]
* Allow reader users to set a dashboard as start page.
https://github.com/Graylog2/graylog2-web-interface/issues/1681[Graylog2/graylog2-web-interface#1681]
* Auto content pack loader – download and install content packs
automatically
* Appliance pre-configured for log ingestion and analysis
* Show a getting started guide on first install.
https://github.com/Graylog2/graylog2-web-interface/issues/1662[Graylog2/graylog2-web-interface#1662]
* Include role permissions in “/roles/\{rolename}/members” REST API
endpoint.
https://github.com/Graylog2/graylog2-server/issues/1549[Graylog2/graylog2-server#1549]
* Fixed NullPointerException in GELF output.
https://github.com/Graylog2/graylog2-server/issues/1538[Graylog2/graylog2-server#1538]
* Fixed NullPointerException in GELF input handling.
https://github.com/Graylog2/graylog2-server/issues/1544[Graylog2/graylog2-server#1544]
* Use the root user’s timezone for LDAP users by default.
https://github.com/Graylog2/graylog2-server/issues/1000[Graylog2/graylog2-server#1000]
https://github.com/Graylog2/graylog2-server/issues/1554[Graylog2/graylog2-server#1554]
* Fix display of JSON messages.
https://github.com/Graylog2/graylog2-web-interface/issues/1686[Graylog2/graylog2-web-interface#1686]
* Improve search robustness with missing Elasticsearch indices.
https://github.com/Graylog2/graylog2-server/issues/1574[Graylog2/graylog2-server#1547]
https://github.com/Graylog2/graylog2-server/issues/1533[Graylog2/graylog2-server#1533]
* Fixed race condition between index creation and index mapping
configuration.
https://github.com/Graylog2/graylog2-server/issues/1502[Graylog2/graylog2-server#1502]
https://github.com/Graylog2/graylog2-server/issues/1563[Graylog2/graylog2-server#1563]
* Fixed concurrency problem in GELF input handling.
https://github.com/Graylog2/graylog2-server/issues/1561[Graylog2/graylog2-server#1561]
* Fixed issue with widget value calculation.
https://github.com/Graylog2/graylog2-server/issues/1588[Graylog2/graylog2-server#1588]
* Do not extend user sessions when updating widgets.
https://github.com/Graylog2/graylog2-web-interface/issues/1655[Graylog2/graylog2-web-interface#1655]
* Fixed compatibility mode for Internet Explorer.
https://github.com/Graylog2/graylog2-web-interface/issues/1661[Graylog2/graylog2-web-interface#1661]
https://github.com/Graylog2/graylog2-web-interface/issues/1668[Graylog2/graylog2-web-interface#1668]
* Fixed whitespace issue in extractor example.
https://github.com/Graylog2/graylog2-web-interface/issues/1650[Graylog2/graylog2-web-interface#1650]
* Fixed several issues on the indices page.
https://github.com/Graylog2/graylog2-web-interface/issues/1691[Graylog2/graylog2-web-interface#1691]
https://github.com/Graylog2/graylog2-web-interface/issues/1692[Graylog2/graylog2-web-interface#1692]
* Fixed permission issue for stream alert management.
https://github.com/Graylog2/graylog2-web-interface/issues/1659[Graylog2/graylog2-web-interface#1659]
* Fixed deletion of LDAP group mappings when updating LDAP settings.
https://github.com/Graylog2/graylog2-server/issues/1513[Graylog2/graylog2-server#1513]
* Fixed dangling role references after deleting a role
https://github.com/Graylog2/graylog2-server/issues/1608[Graylog2/graylog2-server#1608]
* Support LDAP Group Mapping for Sun Directory Server (new since beta.2)
https://github.com/Graylog2/graylog2-server/issues/1583[Graylog2/graylog2-server#1583]

[[graylog-1.2.2]]
Graylog 1.2.2
~~~~~~~~~~~~~

Released: 2015-10-27

https://www.graylog.org/graylog-1-2-2-is-now-available/

* Fixed a whitespace issue in the extractor UI.
https://github.com/Graylog2/graylog2-web-interface/issues/1650[Graylog2/graylog2-web-interface#1650]
* Fixed the index description on the indices page.
https://github.com/Graylog2/graylog2-web-interface/issues/1653[Graylog2/graylog2-web-interface#1653]
* Fixed a memory leak in the GELF UDP handler code. (Analysis and fix
contributed by @lightpriest and @onyxmaster on GitHub. Thank you!)
https://github.com/Graylog2/graylog2-server/issues/1462[Graylog2/graylog2-server#1462],
https://github.com/Graylog2/graylog2-server/issues/1488[Graylog2/graylog2-server#1488]
* Improved the LDAP group handling code to handle more LDAP setups.
https://github.com/Graylog2/graylog2-server/issues/1433[Graylog2/graylog2-server#1433],
https://github.com/Graylog2/graylog2-server/issues/1453[Graylog2/graylog2-server#1453],
https://github.com/Graylog2/graylog2-server/issues/1491[Graylog2/graylog2-server#1491],
https://github.com/Graylog2/graylog2-server/issues/1494[Graylog2/graylog2-server#1494]
* Fixed email alerts for users with multiple email addresses. (LDAP
setups)
https://github.com/Graylog2/graylog2-server/issues/1439[Graylog2/graylog2-server#1439],
https://github.com/Graylog2/graylog2-server/issues/1492[Graylog2/graylog2-server#1492]
* Improve index range handling performance.
https://github.com/Graylog2/graylog2-server/issues/1465[Graylog2/graylog2-server#1465],
https://github.com/Graylog2/graylog2-server/issues/1493[Graylog2/graylog2-server#1493]
* Fixed JSON extractor with null values.
https://github.com/Graylog2/graylog2-server/issues/1475[Graylog2/graylog2-server#1475],
https://github.com/Graylog2/graylog2-server/issues/1505[Graylog2/graylog2-server#1505]
* Fixed role assignment when updating user via REST API.
https://github.com/Graylog2/graylog2-server/issues/1456[Graylog2/graylog2-server#1456],
https://github.com/Graylog2/graylog2-server/issues/1507[Graylog2/graylog2-server#1507]

[[graylog-1.2.1]]
Graylog 1.2.1
~~~~~~~~~~~~~

Released: 2015-09-22

https://www.graylog.org/graylog-1-2-1-is-now-available/

* Fixed various issues around importing and applying content packs
https://github.com/Graylog2/graylog2-server/issues/1423[Graylog2/graylog2-server#1423],
https://github.com/Graylog2/graylog2-server/issues/1434[Graylog2/graylog2-server#1434],
https://github.com/Graylog2/graylog2-web-interface/issues/1605[Graylog2/graylog2-web-interface#1605],
https://github.com/Graylog2/graylog2-web-interface/pull/1614[Graylog2/graylog2-web-interface#1614]
* Fixed loading existing alarm callbacks that had been created with
Graylog 1.0.x or earlier
https://github.com/Graylog2/graylog2-server/issues/1428[Graylog2/graylog2-server#1428]
* Fixed compatibility problem with Elasticsearch 1.5.x and earlier
https://github.com/Graylog2/graylog2-server/issues/1426[Graylog2/graylog2-server#1426]
* Fixed handling of statistical functions in field graphs
https://github.com/Graylog2/graylog2-web-interface/issues/1604[Graylog2/graylog2-web-interface#1604]
* Use correct title when adding quick values to a dashboard
https://github.com/Graylog2/graylog2-web-interface/issues/1603[Graylog2/graylog2-web-interface#1603]

[[graylog-1.2.0]]
Graylog 1.2.0
~~~~~~~~~~~~~

Released: 2015-09-14

https://www.graylog.org/announcing-graylog-1-2-ga-release-includes-30-new-features/

* Make sure existing role assignments survive on LDAP account sync.
https://github.com/Graylog2/graylog2-server/issues/1405[Graylog2/graylog2-server#1405]
|
https://github.com/Graylog2/graylog2-server/pull/1406[Graylog2/graylog2-server#1406]
* Use memberOf query for ActiveDirectory to speed up LDAP queries.
https://github.com/Graylog2/graylog2-server/pull/1407[Graylog2/graylog2-server#1407]
* Removed disable_index_range_calculation configuration option.
https://github.com/Graylog2/graylog2-server/pull/1411[Graylog2/graylog2-server#1411]
* Avoid potentially long-running Elasticsearch cluster-level operations
by only saving an index range if it actually changed.
https://github.com/Graylog2/graylog2-server/pull/1412[Graylog2/graylog2-server#1412]
* Allow editing the roles of LDAP users.
https://github.com/Graylog2/graylog2-web-interface/pull/1598[Graylog2/graylog2-web-interface#1598]
* Improved quick values widget.
https://github.com/Graylog2/graylog2-web-interface/issues/1487[Graylog2/graylog2-web-interface#1487]

[[graylog-1.2.0-rc.4]]
Graylog 1.2.0-rc.4
~~~~~~~~~~~~~~~~~~

Released: 2015-09-08

https://www.graylog.org/announcing-graylog-1-2-rc-4/

* Deprecated MongoDB storage of internal metrics feature.
* Added customizable LDAP filter for user groups lookup.
https://github.com/Graylog2/graylog2-server/issues/951[Graylog2/graylog2-server#951]
* Allow usage of count and cardinality statistical functions in
dashboard widgets.
https://github.com/Graylog2/graylog2-server/issues/1376[Graylog2/graylog2-server#1376]
* Disabled index range recalculation on every index rotation.
https://github.com/Graylog2/graylog2-server/pull/1388[Graylog2/graylog2-server#1388]
* Added automatic migration of user permissions to admin or reader
roles.
https://github.com/Graylog2/graylog2-server/pull/1389[Graylog2/graylog2-server#1389]
* Fixed widget problem with invalid timestamps.
https://github.com/Graylog2/graylog2-web-interface/issues/1390[Graylog2/graylog2-web-interface#1390]
* Added config option to enable TLS certificate validation in REST
client.
https://github.com/Graylog2/graylog2-server/pull/1393[Graylog2/graylog2-server#1393]
* Fixed rule matching issue in stream routing engine.
https://github.com/Graylog2/graylog2-server/pull/1397[Graylog2/graylog2-server#1397]
* Changed default titles for stream widgets.
https://github.com/Graylog2/graylog2-web-interface/issues/1476[Graylog2/graylog2-web-interface#1476]
* Changed data filters to be case insensitive.
https://github.com/Graylog2/graylog2-web-interface/issues/1585[Graylog2/graylog2-web-interface#1585]
* Improved padding for stack charts.
https://github.com/Graylog2/graylog2-web-interface/issues/1568[Graylog2/graylog2-web-interface#1568]
* Improved resiliency when Elasticsearch is not available.
https://github.com/Graylog2/graylog2-web-interface/issues/1518[Graylog2/graylog2-web-interface#1518]
* Redirect to user edit form after updating a user.
https://github.com/Graylog2/graylog2-web-interface/issues/1588[Graylog2/graylog2-web-interface#1588]
* Improved dashboard widgets error handling.
https://github.com/Graylog2/graylog2-web-interface/pull/1590[Graylog2/graylog2-web-interface#1590]
* Fixed timing issue in streams UI.
https://github.com/Graylog2/graylog2-web-interface/issues/1490[Graylog2/graylog2-web-interface#1490]
* Improved indices overview page.
https://github.com/Graylog2/graylog2-web-interface/pull/1593[Graylog2/graylog2-web-interface#1593]
* Fixed browser back button behavior.
https://github.com/Graylog2/graylog2-web-interface/pull/1594[Graylog2/graylog2-web-interface#1594]
* Fixed accidental type conversion for number configuration fields in
alarmcallback plugins.
https://github.com/Graylog2/graylog2-web-interface/issues/1596[Graylog2/graylog2-web-interface#1596]
* Fixed data type problem for extracted timestamps via grok.
https://github.com/Graylog2/graylog2-server/pull/1403[Graylog2/graylog2-server#1403]

[[graylog-1.2.0-rc.2]]
Graylog 1.2.0-rc.2
~~~~~~~~~~~~~~~~~~

Released: 2015-08-31

https://www.graylog.org/announcing-graylog-1-2-rc/

* Implement global Elasticsearch timeout and add
`elasticsearch_request_timeout` configuration setting.
https://github.com/Graylog2/graylog2-server/issues/1220[Graylog2/graylog2-server#1220]
* Fixed lots of documentation links.
https://github.com/Graylog2/graylog2-server/pull/1238[Graylog2/graylog2-server#1238]
* Groovy shell server removed.
https://github.com/Graylog2/graylog2-server/pull/1266[Graylog2/graylog2-server#1266]
* Lots of index range calculation fixes.
https://github.com/Graylog2/graylog2-server/pull/1274[Graylog2/graylog2-server#1274]
* New Raw AMQP input.
https://github.com/Graylog2/graylog2-server/pull/1280[Graylog2/graylog2-server#1280]
* New Syslog AMQP input.
https://github.com/Graylog2/graylog2-server/pull/1280[Graylog2/graylog2-server#1280]
* Updated bundled Elasticsearch to 1.7.1.
* The fields in configuration dialogs for inputs and outputs are now
ordered.
https://github.com/Graylog2/graylog2-server/issues/1282[Graylog2/graylog2-server#1282]
* Allow server startup without working Elasticsearch cluster.
https://github.com/Graylog2/graylog2-server/issues/1136[Graylog2/graylog2-server#1136],
https://github.com/Graylog2/graylog2-server/pull/1289[Graylog2/graylog2-server#1289]
* Added OR operator to stream matching.
https://github.com/Graylog2/graylog2-server/pull/1292[Graylog2/graylog2-server#1292],
https://github.com/Graylog2/graylog2-web-interface/pull/1552[Graylog2/graylog2-web#1552]
* New stream router engine with better stream matching performance.
https://github.com/Graylog2/graylog2-server/pull/1305[Graylog2/graylog2-server#1305],
https://github.com/Graylog2/graylog2-server/pull/1309[Graylog2/graylog2-server#1309]
* Grok pattern import/export support for content packs.
https://github.com/Graylog2/graylog2-server/pull/1300[Graylog2/graylog2-server#1300],
https://github.com/Graylog2/graylog2-web-interface/pull/1527[Graylog2/graylog2-web#1527]
* Added MessageListCodec interface for codec implementations that can
decode multiple messages from one raw message.
https://github.com/Graylog2/graylog2-server/pull/1307[Graylog2/graylog2-server#1307]
* Added keepalive configuration option for all TCP transports.
https://github.com/Graylog2/graylog2-server/issues/1287[Graylog2/graylog2-server#1287],
https://github.com/Graylog2/graylog2-server/pull/1318[Graylog2/graylog2-server#1318]
* Support for roles and LDAP groups.
https://github.com/Graylog2/graylog2-server/issues/1321[Graylog2/graylog2-server#1321],
https://github.com/Graylog2/graylog2-server/issues/951[Graylog2/graylog2-server#951]
* Added timezone configuration option to date converter.
https://github.com/Graylog2/graylog2-server/issues/1320[Graylog2/graylog2-server#1320],
https://github.com/Graylog2/graylog2-server/pull/1324[Graylog2/graylog2-server#1324]
* Added alarmcallback history feature.
https://github.com/Graylog2/graylog2-server/pull/1313[Graylog2/graylog2-server#1313],
https://github.com/Graylog2/graylog2-web-interface/pull/1537[Graylog2/graylog2-web#1537]
* Added more configuration options to GELF output. (TCP settings, TLS
support)
https://github.com/Graylog2/graylog2-server/pull/1337[Graylog2/graylog2-server#1337],
https://github.com/Graylog2/graylog2-server/issues/979[Graylog2/graylog2-server#979]
* Store timestamp and some other internal fields in Elasticsearch as doc
values. Removed "elasticsearch_store_timestamps_as_doc_values" option
from configuration file.
https://github.com/Graylog2/graylog2-server/issues/1335[Graylog2/graylog2-server#1335],
https://github.com/Graylog2/graylog2-server/pull/1342[Graylog2/graylog2-server#1342]
* Added TLS support for GELF HTTP input.
https://github.com/Graylog2/graylog2-server/pull/1348[Graylog2/graylog2-server#1348]
* Added JSON extractor.
https://github.com/Graylog2/graylog2-server/issues/632[Graylog2/graylog2-server#632],
https://github.com/Graylog2/graylog2-server/pull/1355[Graylog2/graylog2-server#1355],
https://github.com/Graylog2/graylog2-web-interface/pull/1555[Graylog2/graylog2-web#1555]
* Added support for TLS client certificate authentication to all TCP
based inputs.
https://github.com/Graylog2/graylog2-server/pull/1357[Graylog2/graylog2-server#1357],
https://github.com/Graylog2/graylog2-server/pull/1363[Graylog2/graylog2-server#1363]
* Added stacked chart widget.
https://github.com/Graylog2/graylog2-server/pull/1284[Graylog2/graylog2-server#1284],
https://github.com/Graylog2/graylog2-web-interface/pull/1513[Graylog2/graylog2-web#1513]
* Added cardinality option to field histograms.
https://github.com/Graylog2/graylog2-web-interface/pull/1529[Graylog2/graylog2-web#1529],
https://github.com/Graylog2/graylog2-server/pull/1303[Graylog2/graylog2-server#1303]
* Lots of dashboard improvements.
https://github.com/Graylog2/graylog2-web-interface/pull/1550[Graylog2/graylog2-web#1550]
* Replaced Gulp with Webpack.
https://github.com/Graylog2/graylog2-web-interface/pull/1548[Graylog2/graylog2-web#1548]
* Updated to Play 2.3.10.

[[graylog-1.1.6]]
Graylog 1.1.6
~~~~~~~~~~~~~

Released: 2015-08-06

https://www.graylog.org/graylog-1-1-6-released/

* Fix edge case in `SyslogOctetCountFrameDecoder` which caused the
Syslog TCP input to reset connections
(https://github.com/Graylog2/graylog2-server/issues/1105[Graylog2/graylog2-server#1105],
https://github.com/Graylog2/graylog2-server/issues/1339[Graylog2/graylog2-server#1339])
* Properly log errors in the Netty channel pipeline
(https://github.com/Graylog2/graylog2-server/issues/1340[Graylog2/graylog2-server#1340])
* Prevent creation of invalid alert conditions
(https://github.com/Graylog2/graylog2-server/issues/1332[Graylog2/graylog2-server#1332])
* Upgrade to
https://www.elastic.co/blog/elasticsearch-1-7-1-and-1-6-2-released[Elasticsearch
1.6.2]

[[graylog-1.1.5]]
Graylog 1.1.5
~~~~~~~~~~~~~

Released: 2015-07-27

https://www.graylog.org/graylog-1-1-5-released/

* Improve handling of exceptions in the JournallingMessageHandler
(https://github.com/Graylog2/graylog2-server/pull/1286[Graylog2/graylog2-server#1286])
* Upgrade to Elasticsearch 1.6.1
(https://github.com/Graylog2/graylog2-server/pull/1312[Graylog2/graylog2-server#1312])
* Remove hard-coded limit for UDP receive buffer size
(https://github.com/Graylog2/graylog2-server/pull/1290[Graylog2/graylog2-server#1290])
* Ensure that `elasticsearch_index_prefix` is lowercase
(https://github.com/Graylog2/graylog2-server/commit/21732256ac36f9567be1605f533ebbba7f363468[commit
2173225] )
* Add configuration option for time zone to `Date` converter
(https://github.com/Graylog2/graylog2-server/issues/1320[Graylog2/graylog2-server#1320])
* Fix NPE if the disk journal is disabled on a node
(https://github.com/Graylog2/graylog2-web-interface/pull/1520[Graylog2/graylog2-web-interface#1520])
* Statistic and Chart error: Adding time zone offset caused overflow
(https://github.com/Graylog2/graylog2-server/issues/1257[Graylog2/graylog2-server#1257])
* Ignore stream alerts and throughput on serialize
(https://github.com/Graylog2/graylog2-server/pull/1309[Graylog2/graylog2-server#1309])
* Fix dynamic keyword time-ranges for dashboard widgets created from
content packs
(https://github.com/Graylog2/graylog2-server/pull/1308[Graylog2/graylog2-server#1308])
* Upgraded Anonymous Usage Statistics plugin to version 1.1.1

[[graylog-1.1.4]]
Graylog 1.1.4
~~~~~~~~~~~~~

Released: 2015-06-30

https://www.graylog.org/graylog-v1-1-4-is-now-available/

* Make heartbeat timeout option for AmqpTransport optional.
https://github.com/Graylog2/graylog2-server/issues/1010[Graylog2/graylog2-server#1010]
* Export as CSV on stream fails with "Invalid range type provided."
https://github.com/Graylog2/graylog2-web-interface/issues/1504[Graylog2/graylog2-web-interface#1504]

[[graylog-1.1.3]]
Graylog 1.1.3
~~~~~~~~~~~~~

Released: 2015-06-19

https://www.graylog.org/graylog-v1-1-3-is-now-available/

* Log error message early if there is a MongoDB connection error.
https://github.com/Graylog2/graylog2-server/issues/1249[Graylog2/graylog2-server#1249]
* Fixed field content value alert condition.
https://github.com/Graylog2/graylog2-server/issues/1245[Graylog2/graylog2-server#1245]
* Extend warning about SO_RCVBUF size to UDP inputs.
https://github.com/Graylog2/graylog2-server/issues/1243[Graylog2/graylog2-server#1243]
* Scroll on button dropdowns.
https://github.com/Graylog2/graylog2-web-interface/issues/1477[Graylog2/graylog2-web-interface#1477]
* Normalize graph widget numbers before drawing them.
https://github.com/Graylog2/graylog2-web-interface/issues/1479[Graylog2/graylog2-web-interface#1479]
* Fix highlight result checkbox position on old Firefox.
https://github.com/Graylog2/graylog2-web-interface/issues/1440[Graylog2/graylog2-web-interface#1440]
* Unescape terms added to search bar.
https://github.com/Graylog2/graylog2-web-interface/issues/1484[Graylog2/graylog2-web-interface#1484]
* Load another message in edit extractor page not working.
https://github.com/Graylog2/graylog2-web-interface/issues/1488[Graylog2/graylog2-web-interface#1488]
* Reader users aren't able to export search results as CSV.
https://github.com/Graylog2/graylog2-web-interface/issues/1492[Graylog2/graylog2-web-interface#1492]
* List of streams not loaded on message details page.
https://github.com/Graylog2/graylog2-web-interface/issues/1496[Graylog2/graylog2-web-interface#1496]

[[graylog-1.1.2]]
Graylog 1.1.2
~~~~~~~~~~~~~

Released: 2015-06-10

https://www.graylog.org/graylog-v1-1-2-is-now-available/

* Get rid of NoSuchElementException if index alias doesn't exist.
https://github.com/Graylog2/graylog2-server/issues/1218[Graylog2/graylog2-server#1218]
* Make Alarm Callbacks API compatible to Graylog 1.0.x again.
https://github.com/Graylog2/graylog2-server/issues/1221[Graylog2/graylog2-server#1221],
https://github.com/Graylog2/graylog2-server/issues/1222[Graylog2/graylog2-server#1222],
https://github.com/Graylog2/graylog2-server/issues/1224[Graylog2/graylog2-server#1224]
* Fixed issues with natural language parser for keyword time range.
https://github.com/Graylog2/graylog2-server/issues/1226[Graylog2/graylog2-server#1226]
* Unable to write Graylog metrics to MongoDB
https://github.com/Graylog2/graylog2-server/issues/1228[Graylog2/graylog2-server#1228]
* Unable to delete user.
https://github.com/Graylog2/graylog2-server/issues/1209[Graylog2/graylog2-server#1209]
* Unable to unpause streams, dispite editing permissions.
https://github.com/Graylog2/graylog2-web-interface/issues/1456[Graylog2/graylog2-web-interface#1456]
* Choose quick values widget size dynamically.
https://github.com/Graylog2/graylog2-web-interface/issues/1422[Graylog2/graylog2-web-interface#1422]
* Default field sort order is not guaranteed after reload.
https://github.com/Graylog2/graylog2-web-interface/issues/1436[Graylog2/graylog2-web-interface#1436]
* Toggling all fields in search list throws error and breaks pagination.
https://github.com/Graylog2/graylog2-web-interface/issues/1434[Graylog2/graylog2-web-interface#1434]
* Improve multi-line log messages support.
https://github.com/Graylog2/graylog2-web-interface/issues/612[Graylog2/graylog2-web-interface#612]
* NPE when clicking a message from a deleted input on a stopped node.
https://github.com/Graylog2/graylog2-web-interface/issues/1444[Graylog2/graylog2-web-interface#1444]
* Auto created search syntax must use quotes for values with whitespaces
in them.
https://github.com/Graylog2/graylog2-web-interface/issues/1448[Graylog2/graylog2-web-interface#1448]
* Quick Values doesn't update for new field.
https://github.com/Graylog2/graylog2-web-interface/issues/1438[Graylog2/graylog2-web-interface#1438]
* New Quick Values list too large.
https://github.com/Graylog2/graylog2-web-interface/issues/1442[Graylog2/graylog2-web-interface#1442]
* Unloading referenced alarm callback plugin breaks alarm callback
listing.
https://github.com/Graylog2/graylog2-web-interface/issues/1450[Graylog2/graylog2-web-interface#1450]
* Add to search button doesn't work as expected for "level" field.
https://github.com/Graylog2/graylog2-web-interface/issues/1453[Graylog2/graylog2-web-interface#1453]
* Treat "*" query as empty query.
https://github.com/Graylog2/graylog2-web-interface/issues/1420[Graylog2/graylog2-web-interface#1420]
* Improve title overflow on widgets.
https://github.com/Graylog2/graylog2-web-interface/issues/1430[Graylog2/graylog2-web-interface#1430]
* Convert NaN to 0 on histograms.
https://github.com/Graylog2/graylog2-web-interface/issues/1417[Graylog2/graylog2-web-interface#1417]
* "&lt;&gt;" values in fields are unescaped and don't display in Quick
Values.
https://github.com/Graylog2/graylog2-web-interface/issues/1455[Graylog2/graylog2-web-interface#1455]
* New quickvalues are not showing number of terms.
https://github.com/Graylog2/graylog2-web-interface/issues/1411[Graylog2/graylog2-web-interface#1411]
* Default index for split &amp; index extractor results in an error.
https://github.com/Graylog2/graylog2-web-interface/issues/1464[Graylog2/graylog2-web-interface#1464]
* Improve behaviour when field graph fails to load.
https://github.com/Graylog2/graylog2-web-interface/issues/1276[Graylog2/graylog2-web-interface#1276]
* Unable to unpause streams, dispite editing permissions.
https://github.com/Graylog2/graylog2-web-interface/issues/1456[Graylog2/graylog2-web-interface#1456]
* Wrong initial size of quick values pie chart.
https://github.com/Graylog2/graylog2-web-interface/issues/1469[Graylog2/graylog2-web-interface#1469]
* Problems refreshing data on quick values pie chart.
https://github.com/Graylog2/graylog2-web-interface/issues/1470[Graylog2/graylog2-web-interface#1470]
* Ignore streams with no permissions on message details.
https://github.com/Graylog2/graylog2-web-interface/issues/1472[Graylog2/graylog2-web-interface#1472]

[[graylog-1.1.1]]
Graylog 1.1.1
~~~~~~~~~~~~~

Released: 2015-06-05

https://www.graylog.org/graylog-v1-1-1-is-now-available/

* Fix problem with missing alarmcallbacks.
https://github.com/Graylog2/graylog2-server/issues/1214[Graylog2/graylog2-server#1214]
* Add additional newline between messages to alert email.
https://github.com/Graylog2/graylog2-server/issues/1216[Graylog2/graylog2-server#1216]
* Fix incorrect index range calculation.
https://github.com/Graylog2/graylog2-server/issues/1217[Graylog2/graylog2-server#1217],
https://github.com/Graylog2/graylog2-web-interface/issues/1266[Graylog2/graylog2-web-interface#1266]
* Fix sidebar auto-height on old Firefox versions.
https://github.com/Graylog2/graylog2-web-interface/issues/1410[Graylog2/graylog2-web-interface#1410]
* Fix "create one now" link on stream list page.
https://github.com/Graylog2/graylog2-web-interface/issues/1424[Graylog2/graylog2-web-interface#1424]
* Do not update StreamThroughput when unmounted.
https://github.com/Graylog2/graylog2-web-interface/issues/1428[Graylog2/graylog2-web-interface#1428]
* Fix position of alert annotations in search result histogram.
https://github.com/Graylog2/graylog2-web-interface/issues/1421[Graylog2/graylog2-web-interface#1421]
* Fix NPE when searching.
https://github.com/Graylog2/graylog2-web-interface/issues/1212[Graylog2/graylog2-web-interface#1212]
* Hide unlock dashboard link for reader users.
https://github.com/Graylog2/graylog2-web-interface/issues/1429[Graylog2/graylog2-web-interface#1429]
* Open radio documentation link on a new window.
https://github.com/Graylog2/graylog2-web-interface/issues/1427[Graylog2/graylog2-web-interface#1427]
* Use radio node page on message details.
https://github.com/Graylog2/graylog2-web-interface/issues/1423[Graylog2/graylog2-web-interface#1423]

[[graylog-1.1.0]]
Graylog 1.1.0
~~~~~~~~~~~~~

Released: 2015-06-04

https://www.graylog.org/graylog-1-1-is-now-generally-available/

* Properly set `node_id` on message input
https://github.com/Graylog2/graylog2-server/issues/1210[Graylog2/graylog2-server#1210]
* Fixed handling of booleans in configuration forms in the web interface
* Various design fixes in the web interface

[[graylog-1.1.0-rc.3]]
Graylog 1.1.0-rc.3
~~~~~~~~~~~~~~~~~~

Released: 2015-06-02

https://www.graylog.org/graylog-v1-1-rc3-is-now-available/

* Unbreak server startup with collector thresholds set.
https://github.com/Graylog2/graylog2-server/issues/1194[Graylog2/graylog2-server#1194]
* Adding verbal alert description to alert email templates and subject
line defaults.
https://github.com/Graylog2/graylog2-server/issues/1158[Graylog2/graylog2-server#1158]
* Fix message backlog in default body template in
FormattedEmailAlertSender.
https://github.com/Graylog2/graylog2-server/issues/1163[Graylog2/graylog2-server#1163]
* Make RawMessageEvent's fields volatile to guard against cross-cpu
visibility issues.
https://github.com/Graylog2/graylog2-server/issues/1207[Graylog2/graylog2-server#1207]
* Set default for "disable_index_range_calculation" to "true".
* Passing in value to text area fields in configuration forms.
https://github.com/Graylog2/graylog2-web-interface/issues/1340[Graylog2/graylog2-web-interface#1340]
* Stream list has no loading spinner.
https://github.com/Graylog2/graylog2-web-interface/issues/1309[Graylog2/graylog2-web-interface#1309]
* Showing a helpful notification when there are no active/inactive
collectors.
https://github.com/Graylog2/graylog2-web-interface/issues/1302[Graylog2/graylog2-web-interface#1302]
* Improve behavior when field graphs are stacked.
https://github.com/Graylog2/graylog2-web-interface/issues/1348[Graylog2/graylog2-web-interface#1348]
* Keep new lines added by users on alert callbacks.
https://github.com/Graylog2/graylog2-web-interface/issues/1270[Graylog2/graylog2-web-interface#1270]
* Fix duplicate metrics reporting if two components subscribed to the
same metric on the same page.
https://github.com/Graylog2/graylog2-server/issues/1199[Graylog2/graylog2-server#1199]
* Make sidebar visible on small screens.
https://github.com/Graylog2/graylog2-web-interface/issues/1390[Graylog2/graylog2-web-interface#1390]
* Showing warning and disabling edit button for output if plugin is
missing.
https://github.com/Graylog2/graylog2-web-interface/issues/1185[Graylog2/graylog2-web-interface#1185]
* Using formatted fields in old message loader.
https://github.com/Graylog2/graylog2-web-interface/issues/1393[Graylog2/graylog2-web-interface#1393]
* Several styling and UX improvements

[[graylog-1.1.0-rc.1]]
Graylog 1.1.0-rc.1
~~~~~~~~~~~~~~~~~~

Released: 2015-05-27

https://www.graylog.org/graylog-v1-1-rc1-is-now-available/

* Unable to send email alerts.
https://github.com/Graylog2/graylog2-web-interface/issues/1346[Graylog2/graylog2-web-interface#1346]
* "Show messages from this collector view" displays no messages.
https://github.com/Graylog2/graylog2-web-interface/issues/1334[Graylog2/graylog2-web-interface#1334]
* Exception error in search page when using escaped characters.
https://github.com/Graylog2/graylog2-web-interface/issues/1356[Graylog2/graylog2-web-interface#1356]
* Wrong timestamp on stream rule editor.
https://github.com/Graylog2/graylog2-web-interface/issues/1328[Graylog2/graylog2-web-interface#1328]
* Quickvalue values are not linked to update search query.
https://github.com/Graylog2/graylog2-web-interface/issues/1296[Graylog2/graylog2-web-interface#1296]
* Stream list has no loading spinner.
https://github.com/Graylog2/graylog2-web-interface/issues/1309[Graylog2/graylog2-web-interface#1309]
* Collector list with only inactive collectors is confusing.
https://github.com/Graylog2/graylog2-web-interface/issues/1302[Graylog2/graylog2-web-interface#1302]
* Update sockjs-client to 1.0.0.
https://github.com/Graylog2/graylog2-web-interface/issues/1344[Graylog2/graylog2-web-interface#1344]
* Scroll to search bar when new query term is added.
https://github.com/Graylog2/graylog2-web-interface/issues/1284[Graylog2/graylog2-web-interface#1284]
* Scroll to quick values if not visible.
https://github.com/Graylog2/graylog2-web-interface/issues/1284[Graylog2/graylog2-web-interface#1284]
* Scroll to newly created field graphs.
https://github.com/Graylog2/graylog2-web-interface/issues/1284[Graylog2/graylog2-web-interface#1284]
* Problems with websockets and even xhr streaming.
https://github.com/Graylog2/graylog2-web-interface/issues/1344[Graylog2/graylog2-web-interface#1344],
https://github.com/Graylog2/graylog2-web-interface/issues/1353[Graylog2/graylog2-web-interface#1353],
https://github.com/Graylog2/graylog2-web-interface/issues/1338[Graylog2/graylog2-web-interface#1338],
https://github.com/Graylog2/graylog2-web-interface/issues/1322[Graylog2/graylog2-web-interface#1322]
* Add to search bar not working on sources tab.
https://github.com/Graylog2/graylog2-web-interface/issues/1350[Graylog2/graylog2-web-interface#1350]
* Make field graphs work with streams.
https://github.com/Graylog2/graylog2-web-interface/issues/1352[Graylog2/graylog2-web-interface#1352]
* Improved page design on outputs page.
https://github.com/Graylog2/graylog2-web-interface/issues/1236[Graylog2/graylog2-web-interface#1236]
* Set startpage button missing for dashboards.
https://github.com/Graylog2/graylog2-web-interface/issues/1345[Graylog2/graylog2-web-interface#1345]
* Generating chart for http response code is broken.
https://github.com/Graylog2/graylog2-web-interface/issues/1358[Graylog2/graylog2-web-interface#1358]

[[graylog-1.1.0-beta.3]]
Graylog 1.1.0-beta.3
~~~~~~~~~~~~~~~~~~~~

Released: 2015-05-27

https://www.graylog.org/graylog-1-1-beta-3-is-now-available/

* Kafka inputs now support syslog, GELF and raw messages
https://github.com/Graylog2/graylog2-server/issues/322[Graylog2/graylog2-server#322]
* Configurable timezone for the flexdate converter in extractors.
https://github.com/Graylog2/graylog2-server/issues/1166[Graylog2/graylog2-server#1166]
* Allow decimal values for greater/smaller stream rules.
https://github.com/Graylog2/graylog2-server/issues/1101[Graylog2/graylog2-server#1101]
* New configuration file option to control the default widget cache
time.
https://github.com/Graylog2/graylog2-server/issues/1170[Graylog2/graylog2-server#1170]
* Expose heartbeat configuration for AMQP inputs.
https://github.com/Graylog2/graylog2-server/issues/1010[Graylog2/graylog2-server#1010]
* New alert condition to alert on field content.
https://github.com/Graylog2/graylog2-server/issues/537[Graylog2/graylog2-server#537]
* Add <code>-Dwebsockets.enabled=false</code> option for the web
interface to disable websockets.
https://github.com/Graylog2/graylog2-web-interface/issues/1322[Graylog2/graylog2-web-interface#1322]
* Clicking the Graylog logo redirects to the custom startpage now.
https://github.com/Graylog2/graylog2-web-interface/issues/1315[Graylog2/graylog2-web-interface#1315]
* Improved reset and filter feature in sources tab.
https://github.com/Graylog2/graylog2-web-interface/issues/1337[Graylog2/graylog2-web-interface#1337]
* Fixed issue with stopping Kafka based inputs.
https://github.com/Graylog2/graylog2-server/issues/1171[Graylog2/graylog2-server#1171]
* System throughput resource was always returning 0.
https://github.com/Graylog2/graylog2-web-interface/issues/1313[Graylog2/graylog2-web-interface#1313]
* MongoDB configuration problem with replica sets.
https://github.com/Graylog2/graylog2-server/issues/1173[Graylog2/graylog2-server#1173]
* Syslog parser did not strip empty structured data fields.
https://github.com/Graylog2/graylog2-server/issues/1161[Graylog2/graylog2-server#1161]
* Input metrics did not update after input has been stopped and started
again.
https://github.com/Graylog2/graylog2-server/issues/1187[Graylog2/graylog2-server#1187]
* NullPointerException with existing inputs in database fixed.
https://github.com/Graylog2/graylog2-web-interface/issues/1312[Graylog2/graylog2-web-interface#1312]
* Improved browser input validation for several browsers.
https://github.com/Graylog2/graylog2-web-interface/issues/1318[Graylog2/graylog2-web-interface#1318]
* Grok pattern upload did not work correctly.
https://github.com/Graylog2/graylog2-web-interface/issues/1321[Graylog2/graylog2-web-interface#1321]
* Internet Explorer 9 fixes.
https://github.com/Graylog2/graylog2-web-interface/issues/1319[Graylog2/graylog2-web-interface#1319],
https://github.com/Graylog2/graylog2-web-interface/issues/1320[Graylog2/graylog2-web-interface#1320]
* Quick values feature did not work with reader users.
https://github.com/Graylog2/graylog2-server/issues/1169[Graylog2/graylog2-server#1169]
* Replay link for keyword widgets was broken.
https://github.com/Graylog2/graylog2-web-interface/issues/1323[Graylog2/graylog2-web-interface#1323]
* Provide visual feedback when expanding message details.
https://github.com/Graylog2/graylog2-web-interface/issues/1283[Graylog2/graylog2-web-interface#1283]
* Allow filtering of saved searches again.
https://github.com/Graylog2/graylog2-web-interface/issues/1277[Graylog2/graylog2-web-interface#1277]
* Add back “Show details” link for global input metrics.
https://github.com/Graylog2/graylog2-server/issues/1168[Graylog2/graylog2-server#1168]
* Provide visual feedback when dashboard widgets are loading.
https://github.com/Graylog2/graylog2-web-interface/issues/1324[Graylog2/graylog2-web-interface#1324]
* Restore preview for keyword time range selector.
https://github.com/Graylog2/graylog2-web-interface/issues/1280[Graylog2/graylog2-web-interface#1280]
* Fixed issue where widgets loading data looked empty.
https://github.com/Graylog2/graylog2-web-interface/issues/1324[Graylog2/graylog2-web-interface#1324]

[[graylog-1.1.0-beta.2]]
Graylog 1.1.0-beta.2
~~~~~~~~~~~~~~~~~~~~

Released: 2015-05-20

https://www.graylog.org/graylog-1-1-beta-is-now-available/

* CSV output streaming support including full text message
* Simplified MongoDB configuration with URI support
* Improved tokenizer for extractors
* Configurable UDP buffer size for incoming messages
* Enhanced Grok support with type conversions (integers, doubles and
dates)
* Elasticsearch 1.5.2 support
* Added support for integrated Log Collector
* Search auto-complete
* Manual widget resize
* Auto resize of widgets based on screen size
* Faster search results
* Moved search filter for usability
* Updated several icons to text boxes for usability
* Search highlight toggle
* Pie charts (Stacked charts are coming too!)
* Improved stream management
* Output plugin and Alarm callback edit support
* Dashboard widget search edit
* Dashboard widget direct search button
* Dashboard background update support for better performance
* Log collector status UI

[[graylog-1.0.2]]
Graylog 1.0.2
~~~~~~~~~~~~~

Released: 2015-04-28

https://www.graylog.org/graylog-v1-0-2-has-been-released/

* Regular expression and Grok test failed when example message is a JSON
document or contains special characters
(https://github.com/Graylog2/graylog2-web-interface/issues/1190[Graylog2/graylog2-web-interface#1190],
https://github.com/Graylog2/graylog2-web-interface/issues/1195[Graylog2/graylog2-web-interface#1195])
* "Show message terms" was broken
(https://github.com/Graylog2/graylog2-web-interface/issues/1168[Graylog2/graylog2-web-interface#1168])
* Showing message indices was broken
(https://github.com/Graylog2/graylog2-web-interface/issues/1211[Graylog2/graylog2-web-interface#1211])
* Fixed typo in SetIndexReadOnlyJob
(https://github.com/Graylog2/graylog2-web-interface/issues/1206[Graylog2/graylog2-web-interface#1206])
* Consistent error messages when trying to create graphs from
non-numeric values
(https://github.com/Graylog2/graylog2-web-interface/issues/1210[Graylog2/graylog2-web-interface#1210])
* Fix message about too few file descriptors for Elasticsearch when
number of file descriptors is unlimited
(https://github.com/Graylog2/graylog2-web-interface/issues/1220[Graylog2/graylog2-web-interface#1220])
* Deleting output globally which was assigned to multiple streams left
stale references
(https://github.com/Graylog2/graylog2-server/issues/1113[Graylog2/graylog2-server#1113])
* Fixed problem with sending alert emails
(https://github.com/Graylog2/graylog2-server/issues/1086[Graylog2/graylog2-server#1086])
* TokenizerConverter can now handle mixed quoted and un-quoted k/v pairs
(https://github.com/Graylog2/graylog2-server/issues/1083[Graylog2/graylog2-server#1083])

[[graylog-1.0.1]]
Graylog 1.0.1
~~~~~~~~~~~~~

Released: 2015-03-16

https://www.graylog.org/graylog-v1-0-1-has-been-released/

* Properly log stack traces
(https://github.com/Graylog2/graylog2-server/issues/970[Graylog2/graylog2-server#970])
* Update REST API browser to new Graylog logo
* Avoid spamming the logs if the original input of a message in the disk
journal can't be loaded
(https://github.com/Graylog2/graylog2-server/issues/1005[Graylog2/graylog2-server#1005])
* Allows reader users to see the journal status
(https://github.com/Graylog2/graylog2-server/issues/1009[Graylog2/graylog2-server#1009])
* Compatibility with MongoDB 3.0 and Wired Tiger storage engine
(https://github.com/Graylog2/graylog2-server/issues/1024[Graylog2/graylog2-server#1024])
* Respect `rest_transport_uri` when generating entity URLs in REST API
(https://github.com/Graylog2/graylog2-server/issues/1020[Graylog2/graylog2-server#1020])
* Properly map `NodeNotFoundException`
(https://github.com/Graylog2/graylog2-web-interface/issues/1137[Graylog2/graylog2-web-interface#1137])
* Allow replacing all existing Grok patterns on bulk import
(https://github.com/Graylog2/graylog2-web-interface/pull/1150[Graylog2/graylog2-web-interface#1150])
* Configuration option for discarding messages on error in AMQP inputs
(https://github.com/Graylog2/graylog2-server/issues/1018[Graylog2/graylog2-server#1018])
* Configuration option of maximum HTTP chunk size for HTTP-based inputs
(https://github.com/Graylog2/graylog2-server/issues/1011[Graylog2/graylog2-server#1011])
* Clone alarm callbacks when cloning a stream
(https://github.com/Graylog2/graylog2-server/issues/990[Graylog2/graylog2-server#990])
* Add `hasField()` and `getField()` methods to `MessageSummary` class
(https://github.com/Graylog2/graylog2-server/issues/923[Graylog2/graylog2-server#923])
* Add per input parse time metrics
(https://github.com/Graylog2/graylog2-web-interface/issues/1106[Graylog2/graylog2-web-interface#1106])
* Allow the use of https://logging.apache.org/log4j/extras/ log4j-extras
classes in log4j configuration
(https://github.com/Graylog2/graylog2-server/issues/1042[Graylog2/graylog2-server#1042])
* Fix updating of input statistics for Radio nodes
(https://github.com/Graylog2/graylog2-web-interface/issues/1122[Graylog2/graylog2-web-interface#1022])
* Emit proper error message when a regular expression in an Extractor
doesn't match example message
(https://github.com/Graylog2/graylog2-web-interface/issues/1157[Graylog2/graylog2-web-interface#1157])
* Add additional information to system jobs
(https://github.com/Graylog2/graylog2-server/issues/920[Graylog2/graylog2-server#920])
* Fix false positive message on LDAP login test
(https://github.com/Graylog2/graylog2-web-interface/issues/1138[Graylog2/graylog2-web-interface#1138])
* Calculate saved search resolution dynamically
(https://github.com/Graylog2/graylog2-web-interface/issues/943[Graylog2/graylog2-web-interface#943])
* Only enable LDAP test buttons when data is present
(https://github.com/Graylog2/graylog2-web-interface/issues/1097[Graylog2/graylog2-web-interface#1097])
* Load more than 1 message on Extractor form
(https://github.com/Graylog2/graylog2-web-interface/issues/1105[Graylog2/graylog2-web-interface#1105])
* Fix NPE when listing alarm callback using non-existent plugin
(https://github.com/Graylog2/graylog2-web-interface/issues/1152[Graylog2/graylog2-web-interface#1152])
* Redirect to nodes overview when node is not found
(https://github.com/Graylog2/graylog2-web-interface/issues/1137[Graylog2/graylog2-web-interface#1137])
* Fix documentation links to integrations and data sources
(https://github.com/Graylog2/graylog2-web-interface/issues/1136[Graylog2/graylog2-web-interface#1136])
* Prevent accidental indexing of web interface by web crawlers
(https://github.com/Graylog2/graylog2-web-interface/issues/1151[Graylog2/graylog2-web-interface#1151])
* Validate grok pattern name on the client to avoid duplicate names
(https://github.com/Graylog2/graylog2-server/issues/937[Graylog2/graylog2-server#937])
* Add message journal usage to nodes overview page
(https://github.com/Graylog2/graylog2-web-interface/issues/1083[Graylog2/graylog2-web-interface#1083])
* Properly format numbers according to locale
(https://github.com/Graylog2/graylog2-web-interface/issues/1128[Graylog2/graylog2-web-interface#1128],
https://github.com/Graylog2/graylog2-web-interface/issues/1129[Graylog2/graylog2-web-interface#1129])

[[graylog-1.0.0]]
Graylog 1.0.0
~~~~~~~~~~~~~

Released: 2015-02-19

https://www.graylog.org/announcing-graylog-v1-0-ga/

* No changes since Graylog 1.0.0-rc.4

[[graylog-1.0.0-rc.4]]
Graylog 1.0.0-rc.4
~~~~~~~~~~~~~~~~~~

Released: 2015-02-13

https://www.graylog.org/graylog-v1-0-rc-4-has-been-released/

* Default configuration file locations have changed.
https://github.com/Graylog2/graylog2-server/pull/950[Graylog2/graylog2-server#950]
* Improved error handling on search errors.
https://github.com/Graylog2/graylog2-server/pull/954[Graylog2/graylog2-server#954]
* Dynamically update dashboard widgets with keyword range.
https://github.com/Graylog2/graylog2-server/pull/956[Graylog2/graylog2-server#956],
https://github.com/Graylog2/graylog2-web-interface/issues/958[Graylog2/graylog2-web-interface#958]
* Prevent duplicate loading of plugins.
https://github.com/Graylog2/graylog2-server/pull/948[Graylog2/graylog2-server#948]
* Fixed password handling when editing inputs.
https://github.com/Graylog2/graylog2-web-interface/issues/1103[Graylog2/graylog2-web-interface#1103]
* Fixed issues getting Elasticsearch cluster health.
https://github.com/Graylog2/graylog2-server/issues/953[Graylog2/graylog2-server#953]
* Better error handling for extractor imports.
https://github.com/Graylog2/graylog2-server/issues/942[Graylog2/graylog2-server#942]
* Fixed structured syslog parsing of keys containing special characters.
https://github.com/Graylog2/graylog2-server/issues/845[Graylog2/graylog2-server#845]
* Improved layout on Grok patterns page.
https://github.com/Graylog2/graylog2-web-interface/issues/1109[Graylog2/graylog2-web-interface#1109]
* Improved formatting large numbers.
https://github.com/Graylog2/graylog2-web-interface/issues/1111[Graylog2/graylog2-web-interface#1111]
* New Graylog logo.

[[graylog-1.0.0-rc.3]]
Graylog 1.0.0-rc.3
~~~~~~~~~~~~~~~~~~

Released: 2015-02-05

https://www.graylog.org/graylog-v1-0-rc-3-has-been-released/

* Fixed compatibility with MongoDB version 2.2.
https://github.com/Graylog2/graylog2-server/issues/941[Graylog2/graylog2-server#941]
* Fixed performance regression in process buffer handling.
https://github.com/Graylog2/graylog2-server/issues/944[Graylog2/graylog2-server#944]
* Fixed data type for the `max_size_per_index` config option value.
https://github.com/Graylog2/graylog2-web-interface/issues/1100[Graylog2/graylog2-web-interface#1100]
* Fixed problem with indexer error page.
https://github.com/Graylog2/graylog2-web-interface/issues/1102[Graylog2/graylog2-web-interface#1102]

[[graylog-1.0.0-rc.2]]
Graylog 1.0.0-rc.2
~~~~~~~~~~~~~~~~~~

Released: 2015-02-04

https://www.graylog.org/graylog-v1-0-rc-2-has-been-released/

* Better Windows compatibility.
https://github.com/Graylog2/graylog2-server/issues/930[Graylog2/graylog2-server#930]
* Added helper methods for the plugin API to simplify plugin
development.
* Fixed problem with input removal on radio nodes.
https://github.com/Graylog2/graylog2-server/issues/932[Graylog2/graylog2-server#932]
* Improved buffer information for input, process and output buffers.
https://github.com/Graylog2/graylog2-web-interface/issues/1096[Graylog2/graylog2-web-interface#1096]
* Fixed API return value incompatibility regarding node objects.
https://github.com/Graylog2/graylog2-server/issues/933[Graylog2/graylog2-server#933]
* Fixed reloading of LDAP settings.
https://github.com/Graylog2/graylog2-server/issues/934[Graylog2/graylog2-server#934]
* Fixed ordering of message input state labels.
https://github.com/Graylog2/graylog2-web-interface/issues/1094[Graylog2/graylog2-web-interface#1094]
* Improved error messages for journal related errors.
https://github.com/Graylog2/graylog2-server/issues/931[Graylog2/graylog2-server#931]
* Fixed browser compatibility for stream rules form.
https://github.com/Graylog2/graylog2-web-interface/issues/1095[Graylog2/graylog2-web-interface#1095]
* Improved grok pattern management.
https://github.com/Graylog2/graylog2-web-interface/issues/1099[Graylog2/graylog2-web-interface#1099],
https://github.com/Graylog2/graylog2-web-interface/issues/1098[Graylog2/graylog2-web-interface#1098]

[[graylog-1.0.0-rc.1]]
Graylog 1.0.0-rc.1
~~~~~~~~~~~~~~~~~~

Released: 2015-01-28

https://www.graylog.org/graylog-v1-0-rc-1-has-been-released/

* Cleaned up internal metrics when input is terminating.
https://github.com/Graylog2/graylog2-server/issues/915[Graylog2/graylog2-server#915]
* Added Telemetry plugin options to example graylog.conf.
https://github.com/Graylog2/graylog2-server/issues/914[Graylog2/graylog2-server#914]
* Fixed problems with user permissions on streams.
https://github.com/Graylog2/graylog2-web-interface/issues/1058[Graylog2/graylog2-web-interface#1058]
* Added information about different rotation strategies to REST API.
https://github.com/Graylog2/graylog2-server/issues/913[Graylog2/graylog2-server#913]
* Added better error messages for failing inputs.
https://github.com/Graylog2/graylog2-web-interface/issues/1056[Graylog2/graylog2-web-interface#1056]
* Fixed problem with JVM options in `bin/radioctl` script.
https://github.com/Graylog2/graylog2-server/issues/918[Graylog2/graylog2-server#918]
* Fixed issue with updating input configuration.
https://github.com/Graylog2/graylog2-server/issues/919[Graylog2/graylog2-server#919]
* Fixed password updating for reader users by the admin.
https://github.com/Graylog2/graylog2-web-interface/issues/1075[Graylog2/graylog2-web-interface#1075]
* Enabled the `message_journal_enabled` config option by default.
https://github.com/Graylog2/graylog2-server/issues/924[Graylog2/graylog2-server#924]
* Add REST API endpoint to list reopened indices.
https://github.com/Graylog2/graylog2-web-interface/issues/1072[Graylog2/graylog2-web-interface#1072]
* Fixed problem with GELF stream output.
https://github.com/Graylog2/graylog2-server/issues/921[Graylog2/graylog2-server#921]
* Show an error message on the indices page if the Elasticsearch cluster
is not available.
https://github.com/Graylog2/graylog2-web-interface/issues/1070[Graylog2/graylog2-web-interface#1070]
* Fixed a problem with stopping inputs.
https://github.com/Graylog2/graylog2-server/issues/926[Graylog2/graylog2-server#926]
* Changed output configuration display to mask passwords.
https://github.com/Graylog2/graylog2-web-interface/issues/1066[Graylog2/graylog2-web-interface#1066]
* Disabled message journal on radio nodes.
https://github.com/Graylog2/graylog2-server/issues/927[Graylog2/graylog2-server#927]
* Create new message representation format for search results in alarm
callback messages.
https://github.com/Graylog2/graylog2-server/issues/923[Graylog2/graylog2-server#923]
* Fixed stream router to update the stream engine if a stream has been
changed.
https://github.com/Graylog2/graylog2-server/issues/922[Graylog2/graylog2-server#922]
* Fixed focus problem in stream rule modal windows.
https://github.com/Graylog2/graylog2-web-interface/issues/1063[Graylog2/graylog2-web-interface#1063]
* Do not show new dashboard link for reader users.
https://github.com/Graylog2/graylog2-web-interface/issues/1057[Graylog2/graylog2-web-interface#1057]
* Do not show stream output menu for reader users.
https://github.com/Graylog2/graylog2-web-interface/issues/1059[Graylog2/graylog2-web-interface#1059]
* Do not show user forms of other users for reader users.
https://github.com/Graylog2/graylog2-web-interface/issues/1064[Graylog2/graylog2-web-interface#1064]
* Do not show permission settings in the user profile for reader users.
https://github.com/Graylog2/graylog2-web-interface/issues/1055[Graylog2/graylog2-web-interface#1055]
* Fixed extractor edit form with no messages available.
https://github.com/Graylog2/graylog2-web-interface/issues/1061[Graylog2/graylog2-web-interface#1061]
* Fixed problem with node details page and JVM locale settings.
https://github.com/Graylog2/graylog2-web-interface/issues/1062[Graylog2/graylog2-web-interface#1062]
* Improved page layout for Grok patterns.
* Improved layout for the message journal information.
https://github.com/Graylog2/graylog2-web-interface/issues/1084[Graylog2/graylog2-web-interface#1084],
https://github.com/Graylog2/graylog2-web-interface/issues/1085[Graylog2/graylog2-web-interface#1085]
* Fixed wording on radio inputs page.
https://github.com/Graylog2/graylog2-web-interface/issues/1077[Graylog2/graylog2-web-interface#1077]
* Fixed formatting on indices page.
https://github.com/Graylog2/graylog2-web-interface/issues/1086[Graylog2/graylog2-web-interface#1086]
* Improved error handling in stream rule form.
https://github.com/Graylog2/graylog2-web-interface/issues/1076[Graylog2/graylog2-web-interface#1076]
* Fixed time range selection problem for the sources page.
https://github.com/Graylog2/graylog2-web-interface/issues/1080[Graylog2/graylog2-web-interface#1080]
* Several improvements regarding permission checks for user creation.
https://github.com/Graylog2/graylog2-web-interface/issues/1088[Graylog2/graylog2-web-interface#1088]
* Do not show stream alert test button for reader users.
https://github.com/Graylog2/graylog2-web-interface/issues/1089[Graylog2/graylog2-web-interface#1089]
* Fixed node processing status not updating on the nodes page.
https://github.com/Graylog2/graylog2-web-interface/issues/1090[Graylog2/graylog2-web-interface#1090]
* Fixed filename handling on Windows.
https://github.com/Graylog2/graylog2-server/issues/928[Graylog2/graylog2-server#928],
https://github.com/Graylog2/graylog2-server/issues/732[Graylog2/graylog2-server#732]

[[graylog-1.0.0-beta.2]]
Graylog 1.0.0-beta.2
~~~~~~~~~~~~~~~~~~~~

Released: 2015-01-21

https://www.graylog.org/graylog-v1-0-beta-3-has-been-released/

* Fixed stream alert creation.
https://github.com/Graylog2/graylog2-server/issues/891[Graylog2/graylog2-server#891]
* Suppress warning message when PID file doesn't exist.
https://github.com/Graylog2/graylog2-server/issues/889[Graylog2/graylog2-server#889]
* Fixed an error on outputs page with missing output plugin.
https://github.com/Graylog2/graylog2-server/issues/894[Graylog2/graylog2-server#894]
* Change default heap and garbage collector settings in scripts.
* Add extractor information to log message about failing extractor.
* Fixed problem in SplitAndIndexExtractor.
https://github.com/Graylog2/graylog2-server/issues/896[Graylog2/graylog2-server#896]
* Improved rendering time for indices page.
https://github.com/Graylog2/graylog2-web-interface/issues/1060[Graylog2/graylog2-web-interface#1060]
* Allow user to edit its own preferences.
https://github.com/Graylog2/graylog2-web-interface/issues/1049[Graylog2/graylog2-web-interface#1049]
* Fixed updating stream attributes.
https://github.com/Graylog2/graylog2-server/issues/902[Graylog2/graylog2-server#902]
* Stream throughput now shows combined value over all nodes.
https://github.com/Graylog2/graylog2-web-interface/issues/1047[Graylog2/graylog2-web-interface#1047]
* Fixed resource leak in JVM PermGen memory.
https://github.com/Graylog2/graylog2-server/issues/907[Graylog2/graylog2-server#907]
* Update to gelfclient-1.1.0 to fix DNS resolving issue.
https://github.com/Graylog2/graylog2-server/issues/882[Graylog2/graylog2-server#882]
* Allow arbitrary characters in user names (in fact in any resource
url).
https://github.com/Graylog2/graylog2-web-interface/issues/1005[Graylog2/graylog2-web-interface#1005],
https://github.com/Graylog2/graylog2-web-interface/issues/1006[Graylog2/graylog2-web-interface#1006]
* Fixed search result CSV export.
https://github.com/Graylog2/graylog2-server/issues/901[Graylog2/graylog2-server#901]
* Skip GC collection notifications for parallel collector.
https://github.com/Graylog2/graylog2-server/issues/899[Graylog2/graylog2-server#899]
* Shorter reconnect timeout for Radio AMQP connections.
https://github.com/Graylog2/graylog2-server/issues/900[Graylog2/graylog2-server#900]
* Fixed random startup error in Radio.
https://github.com/Graylog2/graylog2-server/issues/911[Graylog2/graylog2-server#911]
* Fixed updating an alert condition.
https://github.com/Graylog2/graylog2-server/issues/912[Graylog2/graylog2-server#912]
* Add system notifications for journal related warnings.
https://github.com/Graylog2/graylog2-server/issues/897[Graylog2/graylog2-server#897]
* Add system notifications for failing outputs.
https://github.com/Graylog2/graylog2-server/issues/741[Graylog2/graylog2-server#741]
* Improve search result pagination.
https://github.com/Graylog2/graylog2-web-interface/issues/834[Graylog2/graylog2-web-interface#834]
* Improved regex error handling in extractor testing.
https://github.com/Graylog2/graylog2-web-interface/issues/1044[Graylog2/graylog2-web-interface#1044]
* Wrap long names for node metrics.
https://github.com/Graylog2/graylog2-web-interface/issues/1028[Graylog2/graylog2-web-interface#1028]
* Fixed node information progress bars.
https://github.com/Graylog2/graylog2-web-interface/issues/1046[Graylog2/graylog2-web-interface#1046]
* Improve node buffer utilization readability.
https://github.com/Graylog2/graylog2-web-interface/issues/1046[Graylog2/graylog2-web-interface#1046]
* Fixed username alert receiver form field.
https://github.com/Graylog2/graylog2-web-interface/pull/1050[Graylog2/graylog2-web-interface#1050]
* Wrap long messages without break characters.
https://github.com/Graylog2/graylog2-web-interface/issues/1052[Graylog2/graylog2-web-interface#1052]
* Hide list of node plugins if there aren't any plugins installed.
* Warn user before leaving page with unpinned graphs.
https://github.com/Graylog2/graylog2-web-interface/issues/808[Graylog2/graylog2-web-interface#808]

[[graylog-1.0.0-beta.2-1]]
Graylog 1.0.0-beta.2
~~~~~~~~~~~~~~~~~~~~

Released: 2015-01-16

https://www.graylog.org/graylog-v1-0-0-beta2/

* SIGAR native libraries are now found correctly (for getting system
information)
* plugins can now state if they want to run in server or radio
* Fixed LDAP settings testing.
https://github.com/Graylog2/graylog2-web-interface/issues/1026[Graylog2/graylog2-web-interface#1026]
* Improved RFC5425 syslog message parsing.
https://github.com/Graylog2/graylog2-server/issues/845[Graylog2/graylog2-server#845]
* JVM arguments are now being logged on start.
https://github.com/Graylog2/graylog2-server/issues/875[Graylog2/graylog2-server#875]
* Improvements to log messages when Elasticsearch connection fails
during start.
* Fixed an issue with AMQP transport shutdown.
https://github.com/Graylog2/graylog2-server/issues/874[Graylog2/graylog2-server#874]
* After index cycling the System overview page could be broken.
https://github.com/Graylog2/graylog2-server/issues/880[Graylog2/graylog2-server#880]
* Extractors can now be edited.
https://github.com/Graylog2/graylog2-web-interface/issues/549[Graylog2/graylog2-web-interface#549]
* Fixed saving user preferences.
https://github.com/Graylog2/graylog2-web-interface/issues/1027[Graylog2/graylog2-web-interface#1027]
* Scripts now return proper exit codes.
https://github.com/Graylog2/graylog2-server/pull/886[Graylog2/graylog2-server#886]
* Grok patterns can now be uploaded in bulk.
https://github.com/Graylog2/graylog2-server/issues/377[Graylog2/graylog2-server#377]
* During extractor creation the test display could be offset.
https://github.com/Graylog2/graylog2-server/issues/804[Graylog2/graylog2-server#804]
* Performance fix for the System/Indices page.
https://github.com/Graylog2/graylog2-web-interface/issues/1035[Graylog2/graylog2-web-interface#1035]
* A create dashboard link was shown to reader users, leading to an error
when followed.
https://github.com/Graylog2/graylog2-web-interface/issues/1032[Graylog2/graylog2-web-interface#1032]
* Content pack section was shown to reader users, leading to an error
when followed.
https://github.com/Graylog2/graylog2-web-interface/issues/1033[Graylog2/graylog2-web-interface#1033]
* Failing stream outputs were being restarted constantly.
https://github.com/Graylog2/graylog2-server/issues/741[Graylog2/graylog2-server#741]

[[graylog2-0.92.4]]
Graylog2 0.92.4
~~~~~~~~~~~~~~~

Released: 2015-01-14

https://www.graylog.org/graylog2-v0-92-4/

* [SERVER] Ensure that Radio inputs can only be started on server nodes
(https://github.com/Graylog2/graylog2-server/issues/843[Graylog2/graylog2-server#843])
* [SERVER] Avoid division by zero when finding rotation anchor in the
time-based rotation strategy
(https://github.com/Graylog2/graylog2-server/issues/836[Graylog2/graylog2-server#836])
* [SERVER] Use username as fallback if display name in LDAP is empty
(https://github.com/Graylog2/graylog2-server/issues/837[Graylog2/graylog2-server#837])

[[graylog-1.0.0-beta.1]]
Graylog 1.0.0-beta.1
~~~~~~~~~~~~~~~~~~~~

Released: 2015-01-12

https://www.graylog.org/graylog-v1-0-0-beta1/

* Message Journaling
* New Widgets
* Grok Extractor Support
* Overall stability and resource efficiency improvements
* Single binary for `graylog2-server` and `graylog2-radio`
* Inputs are now editable
* Order of field charts rendered inside the search results page is now
maintained.
* Improvements in focus and keyboard behaviour on modal windows and
forms.
* You can now define whether to disable expensive, frequent real-time
updates of the UI in the settings of each user. (For example the
updating of total messages in the system)
* Experimental search query auto-completion that can be enabled in the
user preferences.
* The API browser now documents server response payloads in a better way
so you know what to expect as an answer to your call.
* Now using the standard Java ServiceLoader for plugins.

[[graylog2-0.92.3]]
Graylog2 0.92.3
~~~~~~~~~~~~~~~

Released: 2014-12-23

https://www.graylog.org/graylog2-v0-92-3/

* [SERVER] Removed unnecessary instrumentation in certain places to
reduce GC pressure caused by many short living objects
(https://github.com/Graylog2/graylog2-server/issues/800[Graylog2/graylog2-server#800])
* [SERVER] Limit Netty worker thread pool to 16 threads by default (see
`rest_worker_threads_max_pool_size` in
https://github.com/Graylog2/graylog2-server/blob/0.92.3/misc/graylog2.conf#L71-L72[graylog2.conf]
* [WEB] Fixed upload of content packs when a URI path prefix
(`application.context` in
https://github.com/Graylog2/graylog2-web-interface/blob/0.92.3/misc/graylog2-web-interface.conf.example#L25-L26[graylog2-web-interface.conf])
is being used
(https://github.com/Graylog2/graylog2-web-interface/issues/1009[Graylog2/graylog2-web-interface#1009])
* [WEB] Fixed display of metrics of type Counter
(https://github.com/Graylog2/graylog2-server/issues/795[Graylog2/graylog2-server#795])

[[graylog2-0.92.1]]
Graylog2 0.92.1
~~~~~~~~~~~~~~~

Released: 2014-12-11

https://www.graylog.org/graylog2-v0-92-1/

* [SERVER] Fixed name resolution and overriding sources for network
inputs.
* [SERVER] Fixed wrong delimiter in GELF TCP input.
* [SERVER] Disabled the output cache by default. The output cache is the
source of all sorts of interesting problems. If you want to keep using
it, please read the upgrade notes.
* [SERVER] Fixed message timestamps in GELF output.
* [SERVER] Fixed connection counter for network inputs.
* [SERVER] Added warning message if the receive buffer size (SO_RECV)
couldn’t be set for network inputs.
* [WEB] Improved keyboard shortcuts with most modal dialogs (e. g.
hitting Enter submits the form instead of just closing the dialogs).
* [WEB] Upgraded to play2-graylog2 1.2.1 (compatible with Play 2.3.x and
Java 7).

[[graylog2-0.92.0]]
Graylog2 0.92.0
~~~~~~~~~~~~~~~

Released: 2014-12-01

https://www.graylog.org/graylog2-v0-92/

* [SERVER] IMPORTANT SECURITY FIX: It was possible to perform LDAP
logins with crafted wildcards. (A big thank you to Jose Tozo who
discovered this issue and disclosed it very responsibly.)
* [SERVER] Generate a system notification if garbage collection takes
longer than a configurable threshold.
* [SERVER] Added several JVM-related metrics.
* [SERVER] Added support for Elasticsearch 1.4.x which brings a lot of
stability and resilience features to Elasticsearch clusters.
* [SERVER] Made version check of Elasticsearch version optional.
Disabling this check is not recommended.
* [SERVER] Added an option to disable optimizing Elasticsearch indices
on index cycling.
* [SERVER] Added an option to disable time-range calculation for indices
on index cycling.
* [SERVER] Lots of other performance enhancements for large setups (i.e.
involving several Radio nodes and multiple Graylog2 Servers).
* [SERVER] Support for Syslog Octet Counting, as used by syslog-ng for
syslog via TCP (#743)
* [SERVER] Improved support for structured syslog messages (#744)
* [SERVER] Bug fixes regarding IPv6 literals in mongodb_replica_set and
elasticsearch_discovery_zen_ping_unicast_hosts
* [WEB] Added additional details to system notification about
Elasticsearch max. open file descriptors.
* [WEB] Fixed several bugs and inconsistencies regarding time zones.
* [WEB] Improved graphs and diagrams
* [WEB] Allow to update dashboards when browser window is not on focus
(#738)
* [WEB] Bug fixes regarding timezone handling
* Numerous internal bug fixes

[[graylog2-0.92.0-rc.1]]
Graylog2 0.92.0-rc.1
~~~~~~~~~~~~~~~~~~~~

Released: 2014-11-21

https://www.graylog.org/graylog2-v0-92-rc-1/

* [SERVER] Generate a system notification if garbage collection takes
longer than a configurable threshold.
* [SERVER] Added several JVM-related metrics.
* [SERVER] Added support for Elasticsearch 1.4.x which brings a lot of
stability and resilience features to Elasticsearch clusters.
* [SERVER] Made version check of Elasticsearch version optional.
Disabling this check is not recommended.
* [SERVER] Added an option to disable optimizing Elasticsearch indices
on index cycling.
* [SERVER] Added an option to disable time-range calculation for indices
on index cycling.
* [SERVER] Lots of other performance enhancements for large setups (i.
e. involving several Radio nodes and multiple Graylog2 Servers).
* [WEB] Upgraded to Play 2.3.6.
* [WEB] Added additional details to system notification about
Elasticsearch max. open file descriptors.
* [WEB] Fixed several bugs and inconsistencies regarding time zones.
* Numerous internal bug fixes

[[graylog2-0.91.3]]
Graylog2 0.91.3
~~~~~~~~~~~~~~~

Released: 2014-11-05

https://www.graylog.org/graylog2-v0-90-3-and-v0-91-3-has-been-released/

* Fixed date and time issues related to DST changes
* Requires Elasticsearch 1.3.4; Elasticsearch 1.3.2 had a bug that can
cause index corruptions.
* The `mongodb_replica_set` configuration variable now supports IPv6
* Messages read from the on-disk caches could be stored with missing
fields

[[graylog2-0.91.3-1]]
Graylog2 0.91.3
~~~~~~~~~~~~~~~

Released: 2014-11-05

https://www.graylog.org/graylog2-v0-90-3-and-v0-91-3-has-been-released/

* Fixed date and time issues related to DST changes
* The `mongodb_replica_set` configuration variable now supports IPv6
* Messages read from the on-disk caches could be stored with missing
fields

[[graylog2-0.92.0-beta.1]]
Graylog2 0.92.0-beta.1
~~~~~~~~~~~~~~~~~~~~~~

Released: 2014-11-05

https://www.graylog.org/graylog2-v0-92-beta-1/

* Content packs
* [SERVER] SSL/TLS support for Graylog2 REST API
* [SERVER] Support for time based retention cleaning of your messages.
The old message count based approach is still the default.
* [SERVER] Support for Syslog Octet Counting, as used by syslog-ng for
syslog via TCP
(https://github.com/Graylog2/graylog2-server/pull/743[Graylog2/graylog2-server#743])
* [SERVER] Improved support for structured syslog messages
(https://github.com/Graylog2/graylog2-server/pull/744[Graylog2/graylog2-server#744])
* [SERVER] Bug fixes regarding IPv6 literals in `mongodb_replica_set`
and `elasticsearch_discovery_zen_ping_unicast_hosts`
* [WEB] Revamped "Sources" page in the web interface
* [WEB] Improved graphs and diagrams
* [WEB] Allow to update dashboards when browser window is not on focus
(https://github.com/Graylog2/graylog2-web-interface/issues/738[Graylog2/graylog2-web-interface#738])
* [WEB] Bug fixes regarding timezone handling
* Numerous internal bug fixes

[[graylog2-0.91.1]]
Graylog2 0.91.1
~~~~~~~~~~~~~~~

Released: 2014-10-17

https://www.graylog.org/two-new-graylog2-releases/

* Messages written to the persisted master caches were written to the
system with unreadable timestamps, leading to
* errors when trying to open the message.
* Extractors were only being deleted from running inputs but not from
all inputs
* Output plugins were not always properly loaded
* You can now configure the `alert_check_interval` in your
`graylog2.conf`
* Parsing of configured Elasticsearch unicast discovery addresses could
break when including spaces

[[graylog2-0.90.1]]
Graylog2 0.90.1
~~~~~~~~~~~~~~~

Released: 2014-10-17

https://www.graylog.org/two-new-graylog2-releases/

* Messages written to the persisted master caches were written to the
system with unreadable timestamps, leading to errors when trying to open
the message.
* Extractors were only being deleted from running inputs but not from
all inputs
* Output plugins were not always properly loaded
* You can now configure the `alert_check_interval` in your
`graylog2.conf`
* Parsing of configured Elasticsearch unicast discovery addresses could
break when including spaces

[[graylog2-0.91.0-rc.1]]
Graylog2 0.91.0-rc.1
~~~~~~~~~~~~~~~~~~~~

Released: 2014-09-23

https://www.graylog.org/graylog2-v0-90-has-been-released/

* Optional ElasticSearch v1.3.2 support

[[graylog2-0.90.0]]
Graylog2 0.90.0
~~~~~~~~~~~~~~~

Released: 2014-09-23

https://www.graylog.org/graylog2-v0-90-has-been-released/

* Real-time data forwarding to Splunk or other systems
* Alert callbacks for greater flexibility
* New disk-based architecture for buffering in load spike situations
* Improved graphing
* Plugin API
* Huge performance and stability improvements across the whole stack
* Small possibility of losing messages in certain scenarios has been
fixed
* Improvements to internal logging from threads to avoid swallowing
Graylog2 error messages
* Paused streams are no longer checked for alerts
* Several improvements to timezone handling
* JavaScript performance fixes in the web interface and especially a
fixed memory leak of charts on dashboards
* The GELF HTTP input now supports CORS
* Stream matching now has a configurable timeout to avoid stalling
message processing in case of too complex rules or erroneous regular
expressions
* Stability improvements for Kafka and AMQP inputs
* Inputs can now be paused and resumed
* Dozens of bug fixes and other improvements

[[graylog2-0.20.3]]
Graylog2 0.20.3
~~~~~~~~~~~~~~~

Released: 2014-08-09

https://www.graylog.org/graylog2-v0-20-3-has-been-released/

* Bugfix: Storing saved searches was not accounting custom application
contexts
* Bugfix: Editing stream rules could have a wrong a pre-filled value
* Bugfix: The create dashboard link was shown even if the user has no
permission to so. This caused an ugly error page because of the missing
permissions.
* Bugfix: graylog2-radio could lose numeric fields when writing to the
message broker
* Better default batch size values for the Elasticsearch output
* Improved `rest_transport_uri` default settings to avoid confusion with
loopback interfaces
* The deflector index is now also using the configured index prefix

[[graylog2-0.20.2]]
Graylog2 0.20.2
~~~~~~~~~~~~~~~

Released: 2014-05-24

https://www.graylog.org/graylog2-v0-20-2-has-been-released/

* Search result highlighting
* Reintroduces AMQP support
* Extractor improvements and sharing
* Graceful shutdowns, Lifecycles, Load Balancer integration
* Improved stream alert emails
* Alert annotations
* CSV exports via the REST API now support chunked transfers and avoid
heap size problems with huge result sets
* Login now redirects to page you visited before if there was one
* More live updating information in node detail pages
* Empty dashboards no longer show lock/unlock buttons
* Global inputs now also show IO metrics
* You can now easily copy message IDs into native clipboard with one
click
* Improved message field selection in the sidebar
* Fixed display of floating point numbers in several places
* Now supporting application contexts in the web interface like
`http://example.org/graylog2`
* Several fixes for LDAP configuration form
* Message fields in the search result sidebar now survive pagination
* Only admin users are allowed to change the session timeout for reader
users
* New extractor: Copy whole input
* New converters: uppercase/lowercase, flexdate (tries to parse any
string as date)
* New stream rule to check for presence or absence of fields
* Message processing now supports trace logging
* Better error message for ES discovery problems
* Fixes to GELF HTTP input and it holding open connections
* Some timezone fixes
* CSV exports now only contain selected fields
* Improvements for bin/graylog* control scripts
* UDP inputs now allow for custom receive buffer sizes
* Numeric extractor converter now supports floating point values
* Bugfix: Several small fixes to system notifications and closing them
* Bugfix: Carriage returns were not escaped properly in CSV exports
* Bugfix: Some AJAX calls redirected to the startpage when they failed
* Bugfix: Wrong sorting in sources table
* Bugfix: Quickvalues widget was broken with very long values
* Bugfix: Quickvalues modal was positioned wrong in some cases
* Bugfix: Indexer failures list could break when you had a lot of
failures
* Custom application prefix was not working for field chart analytics
* Bugfix: Memory leaks in the dashboards
* Bugfix: NullPointerException when Elasticsearch discovery failed and
unicast discovery was disabled
* Message backlog in alert emails did not always include the correct
number of messages
* Improvements for message outputs: No longer only waiting for filled
buffers but also flushing them regularly. This avoids problems that make
Graylog2 look like it misses messages in cheap benchmark scenarios
combined with only little throughput.
