[[frequently-asked-questions]]
Frequently asked questions
--------------------------

[[general]]
General
~~~~~~~

[[do-i-need-to-buy-a-license-to-use-graylog]]
Do I need to buy a license to use Graylog?
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

We believe software should be open and accessible to all. You should not
have to pay to analyze your own data, no matter how much you have.

Graylog is licensed under the
http://www.gnu.org/licenses/gpl-3.0.en.html[GNU General Public License].
We do not require license fees for production or non-production use.

[[how-long-do-you-support-older-versions-of-the-graylog-product]]
How long do you support older versions of the Graylog product?
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

For our commercial support customers, we support older versions of
Graylog up to 12 months after the next major release is available. So if
you’re using 1.X, you will continue to receive 1.X support up to a full
year after 2.0 has been released.

[[architecture]]
Architecture
~~~~~~~~~~~~

[[what-is-mongodb-used-for]]
What is MongoDB used for?
^^^^^^^^^^^^^^^^^^^^^^^^^

Graylog uses MongoDB to store your configuration data, not your log
data. Only metadata is stored, such as user information or stream
configurations. None of your log messages are ever stored in MongoDB.
This is why MongoDB does not have a big system impact, and you won’t
have to worry too much about scaling it. With our recommended setup
architecture, MongoDB will simply run alongside your graylog-server
processes and use almost no resources.

We have plans to introduce a database abstraction layer in the future.
This will give you the flexibility to run MongoDB, MySQL or any other
database to store metadata.

[[can-you-guide-me-on-how-to-replicate-mongodb-for-high-availability]]
Can you guide me on how to replicate MongoDB for High Availability?
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

MongoDB actually supplies this information as part of their
documentation. Check out :

* About https://docs.mongodb.org/manual/replication/[MongoDB Replica
Sets].
* How to
https://docs.mongodb.org/manual/tutorial/convert-standalone-to-replica-set/[convert
a standalone MongoDB node to a replica set].

After you've done this, add all MongoDB nodes into the replica_set
configuration in all graylog-server.conf files.

[[i-have-datacenters-across-the-world-and-do-not-want-logs-forwarding-from-everywhere-to-a-central-location-due-to-bandwidth-etc.-how-do-i-handle-this]]
I have datacenters across the world and do not want logs forwarding from
everywhere to a central location due to bandwidth, etc. How do I handle
this?
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

You can have multiple graylog-server instances in a federated structure,
and forward select messages to a centralized GL server.

[[which-load-balancers-do-you-recommend-we-use-with-graylog]]
Which load balancers do you recommend we use with Graylog?
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

You can use any. We have clients running AWS ELB, HAProxy, F5 BIG-IP,
and KEMP.

[[isnt-java-slow-does-it-need-a-lot-of-memory]]
Isn’t Java slow? Does it need a lot of memory?
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

This is a concern that we hear from time to time. We understand Java has
a bad reputation from slow and laggy desktop/GUI applications that eat a
lot of memory. However, we are usually able to prove this assumption
wrong. Well written Java code for server systems is very efficient and
does not need a lot of memory resources.

Give it a try, you might be surprised!

[[does-graylog-encrypt-log-data]]
Does Graylog encrypt log data?
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

All log data is stored in Elasticsearch. They recommend you use
_dm-crypt_ at the file system level. Please see
https://discuss.elastic.co/t/how-should-i-encrypt-data-at-rest-with-elasticsearch/96[here].

[[installation-setup]]
Installation / Setup
~~~~~~~~~~~~~~~~~~~~

[[should-i-download-the-ova-appliances-or-the-separate-packages]]
Should I download the OVA appliances or the separate packages?
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

If you are downloading Graylog for the first time to evaluate it, go for
the appliance. It is really easy, and can be quickly setup so you can
understand if Graylog is right for you. If you are wanting to use
Graylog at some scale in production, and do things like high availabilty
(Mongo replication) we recommend you go for the separate packages.

[[how-do-i-find-out-if-a-specific-log-source-is-supported]]
How do I find out if a specific log source is supported?
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

We support many log sources – and more are coming everyday. For a
complete list, check out https://marketplace.graylog.org/[Graylog
Marketplace], the central repository of Graylog extensions. There are 4
types of content on the Marketplace:

* Plug-Ins: Code that extends Graylog to support a specific use case
that it doesn’t support out of the box.
* Content Pack: A file that can be uploaded into your Graylog system
that sets up streams, inputs, extractors, dashboards, etc. to support a
given log source or use case.
* GELF Library: A library for a programming language or logging
framework that supports sending log messages in GELF format for easy
integration and pre-structured messages.
* Other Solutions: Any other content or guide that helps you integrate
Graylog with an external system or device. For example, how to configure
a specific device to support a format Graylog understands out of the
box.

[[can-i-install-the-graylog-server-on-windows]]
Can I install the Graylog Server on Windows?
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Even though our engineers say it is “technically possible”, don’t do it.
The Graylog server is built using Java, so technically it can run
anywhere. But we currently have it optimized to run better on other
operating systems. If you don’t feel comfortable running your own Linux
system, we recommend you use our Linux virtual appliance which will run
under VMWare.

[[functionality]]
Functionality
~~~~~~~~~~~~~

[[can-graylog-automatically-clean-old-data]]
Can Graylog automatically clean old data?
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Absolutely we have data retention features, please see
here <index_model>.

[[does-graylog-support-ldap-ad-and-its-groups]]
Does Graylog support LDAP / AD and its groups?
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Yup, we’re all over this too with read/write roles and group
permissions. To start, see this <users_and_roles/external_auth>. If you
want to get very granular, you can go through the Graylog REST API.

[[do-we-have-a-user-audit-log-for-compliance]]
Do we have a user audit log for compliance?
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Coming soon in a future release – stay tuned!

[[it-seems-like-graylog-has-no-reporting-functionality]]
It seems like Graylog has no reporting functionality?
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

That’s correct. We currently don’t have built-in reporting functionality
that sends automated reports. However, you can use our REST API to
generate and send you own reports. A cron job and the scripting language
of your choice should do the trick.

[[can-i-filter-inbound-messages-before-they-are-processed-by-the-graylog-server]]
Can I filter inbound messages before they are processed by the Graylog
server?
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Yes, check out our page on how to use blacklisting <blacklisting>.

[[dedicated-partition-for-the-journal]]
Dedicated Partition for the Journal
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

If you create a dedicated Partition for your Kafka Journal, you need to
watch that this is a clean directory. Even _lost+found_ can break it,
for https://github.com/Graylog2/graylog2-server/issues/2348[your
reference].

[[raise-the-java-heap]]
Raise the Java Heap
^^^^^^^^^^^^^^^^^^^

If you need to raise the Java Heap of the Graylog Server or
Elasticsearch in a System that runs as virtual appliances you can use
the advanced settings <graylog_ctl_advanced>.

On Systems that are installed with
DEB / APT <operationg_package_DEB-APT> this setting can be made in
`/etc/defaults/graylog-server`.

Systems that are installed with
RPM / YUM / DNF <operating_package_rpm-yum-dnf> the file is found in
`/etc/sysconfig/graylog-server`.

[[graylog-integrations]]
Graylog & Integrations
~~~~~~~~~~~~~~~~~~~~~~

[[what-is-the-best-way-to-integrate-my-applications-to-graylog]]
What is the best way to integrate my applications to Graylog?
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

We recommend that you use GELF <sending_data>. It's easy for your
application developers and eliminates the need to store the messages
locally. Also, GELF can just send what app person wants so you don't
have to build extractors or do any extra processing in Graylog.

[[i-have-a-log-source-that-creates-dynamic-syslog-messages-based-on-events-and-subtypes-and-grok-patterns-are-difficult-to-use---what-is-the-best-way-to-handle-this]]
I have a log source that creates dynamic syslog messages based on events
and subtypes and grok patterns are difficult to use - what is the best
way to handle this?
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Not a problem! Use our key=value extractor <extractors>.

[[i-want-to-archive-my-log-data.-can-i-write-to-another-database-for-example-hdfs-hadoop-from-graylog]]
I want to archive my log data. Can I write to another database, for
example HDFS / Hadoop, from Graylog?
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Yes, you can output data from Graylog to a different database. We
currently have an HDFS output
https://marketplace.graylog.org/addons/99259226-6ba3-48c8-a710-9598b65eda0e[plug-in]
in the Marketplace - thank you https://github.com/sivasamyk[sivasamyk]!

It’s also easy and fun to write your own <plugins>, which you can then
add to Graylog Marketplace for others to use.

[[i-dont-want-to-use-elasticsearch-as-my-backend-storage-system-can-i-use-another-database-like-mysql-oracle-etc]]
I don’t want to use Elasticsearch as my backend storage system – can I
use another database, like MySQL, Oracle, etc?
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

You can, but we don’t suggest you do. You will not be able to use our
query functionality or our analytic engine on the dataset outside the
system. We only recommend another database if you want it for secondary
storage.

[[troubleshooting]]
Troubleshooting
~~~~~~~~~~~~~~~

[[im-sending-in-messages-and-i-can-see-they-are-being-accepted-by-graylog-but-i-cant-see-them-in-the-search.-what-is-going-wrong]]
I’m sending in messages, and I can see they are being accepted by
Graylog, but I can’t see them in the search. What is going wrong?
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

A common reason for this issue is that the timestamp in the message is
wrong. First, confirm that the message was received by selecting ‘all
messages’ as the time range for your search. Then identify and fix the
source that is sending the wrong timestamp.

[[i-have-configured-an-smtp-server-or-an-output-with-tls-connection-and-receive-handshake-errors.-what-should-i-do]]
I have configured an SMTP server or an output with TLS connection and
receive handshake errors. What should I do?
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Outbound TLS connections have CA (__certification authority__)
certificate verification enabled by default. In case the target server's
certificate is not signed by a CA found from trust store, the connection
will fail. A typical symptom for this is the following error message in
the server logs:

....
Caused by: javax.mail.MessagingException: Could not convert socket to TLS; nested exception is: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
....

This should be corrected by either adding the missing CA certificates to
the Java default trust store (typically found at
`$JAVA_HOME/jre/lib/security/cacerts`), or a custom store that is
configured (by using `-Djavax.net.ssl.trustStore`) for the Graylog
server process. The same procedure applies for both missing valid CAs
and self-signed certificates.

[[suddenly-parts-of-graylog-did-not-work-as-expected]]
Suddenly parts of Graylog did not work as expected
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

If you notice multiple different non working parts in Graylog and found
something like
`java.lang.OutOfMemoryError: unable to create new native thread` in your
Graylog Server logfile, you need to raise the process/thread limit of
the graylog user. The limit can be checked with `ulimit -u` and you need
to check how you can raise `nproc` in your OS.

[[have-another-troubleshooting-question]]
Have another troubleshooting question?
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

See below for some additional support options where you can ask your
question.

[[support]]
Support
~~~~~~~

[[i-think-ive-found-a-bug-how-do-i-report-it]]
I think I’ve found a bug, how do I report it?
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Think you spotted a bug? Oh no! Please report it in our issue trackers
so we can take a look at it. All issue trackers are hosted on
https://github.com/Graylog2[GitHub], tightly coupled to our code and
milestones. Don’t hesitate to open issues – we’ll just close them if
there is nothing to do. We have GitHub repos for the
https://github.com/Graylog2/graylog2-web-interface/issues[web interface]
and the https://github.com/Graylog2/graylog2-server/issues[server].

[[im-having-issues-installing-or-configuring-graylog-where-can-i-go-for-support]]
I’m having issues installing or configuring Graylog, where can I go for
support?
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Check out our Google Group
https://groups.google.com/forum/?hl=en#!forum/graylog2[mailing list] –
you can search for your problem which may already have an answer, or
post a new question.

Another source is the
https://webchat.freenode.net/?channels=%23graylog[#Graylog IRC chat
channel on Freenode]. Our developers and a lot of community members hang
out here. Just join the channel and add any questions, suggestions or
general topics you have.

If you’re looking for professional commercial support from the Graylog
team, we do that too. Please
https://www.graylog.org/professional-support[get in touch here] for more
details.
